cqapi: fixed parsing parameters even when there are unknown arguments between valid one

diff --git a/cqapi b/cqapi
--- a/cqapi
+++ b/cqapi
@@ -169,8 +169,10 @@ while getopts ":Pu:p:i:fcC:" opt; do
     \?)
       if [ $parse -ne 1 ]
       then
-	      echo "Invalid option: -$OPTARG" >&2
-    	  _usage
+           echo "Invalid option: -$OPTARG" >&2
+          _usage
+      else
+          OPTIND=$((OPTIND+1))
       fi;;
     :)
       api=`echo "$OPTARG"|tr -cd 'upi'|wc -c`
