CQM-111 Code review for 1.1.0
* Reformatted all files
* Fixed all scripts based on shellcheck report

diff --git a/cqapi b/cqapi
--- a/cqapi
+++ b/cqapi
@@ -16,8 +16,8 @@
 VERSION=1.1.0
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 CQ UNIX Toolkit API command.
 Version ${VERSION}
 
@@ -58,136 +58,137 @@ exit 1
 
 _curlpath()
 {
-    WHEREIS=`whereis whereis 2>/dev/null|cut -f2 -d ' '`
-    EXITCODE=$?
-    if [ $EXITCODE -ne 0 -o -z "$WHEREIS" ]
+    WHEREIS=$(whereis whereis 2>/dev/null | cut -f2 -d ' ')
+    EXITCODE=${?}
+    if [ ${EXITCODE} -ne 0 -o -z "${WHEREIS}" ]
     then
-        CURLBIN=`which curl`
-        EXITCODE=$?
-        if [ $EXITCODE -ne 0 -o -z "${CURLBIN}" ]
+        CURLBIN=$(which curl)
+        EXITCODE=${?}
+        if [ ${EXITCODE} -ne 0 -o -z "${CURLBIN}" ]
         then
             echo "Cannot locate required command: curl (using which/whereis\
              method)." >&2
             exit 1
         fi
-        echo "$CURLBIN"
+        echo "${CURLBIN}"
         exit 0
     fi
-    CURLBIN=`${WHEREIS} -b curl|cut -f2 -d ' '`
-    EXITCODE=$?
-    if [ -z "$CURLBIN" -o ${EXITCODE} -ne 0 ]
+    CURLBIN=$(${WHEREIS} -b curl | cut -f2 -d ' ')
+    EXITCODE=${?}
+    if [ -z "${CURLBIN}" -o ${EXITCODE} -ne 0 ]
     then
         echo "Cannot locate required command: curl." >&2
         exit 1
     fi
-    echo "$CURLBIN"
+    echo "${CURLBIN}"
     exit
 }
 
 _curlcode()
 {
-	if [ -z "$1" -o "$1" -eq 0 ]
-	then
+    if [ -z "${1}" -o "${1}" -eq 0 ]
+    then
             exit 0
-	fi
-	codes=$(cat <<-'EOF'
-	1 Unsupported protocol. This build of curl has no support for this protocol.
-	2 Failed to initialize.
-	3 URL malformed. The syntax was not correct.
-	4 A feature or option that was needed to perform the desired request was not enabled or was explicitly disabled at build-time. To make curl able to do this, you probably need another build of libcurl!
-	5 Couldn't resolve proxy. The given proxy host could not be resolved.
-	6 Couldn't resolve host. The given remote host was not resolved.
-	7 Failed to connect to host.
-	8 FTP weird server reply. The server sent data curl couldn't parse.
-	9 FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried to change to a directory that doesn't exist on the server.
-	11 FTP weird PASS reply. Curl couldn't parse the reply sent to the PASS request.
-	13 FTP weird PASV reply, Curl couldn't parse the reply sent to the PASV request.
-	14 FTP weird 227 format. Curl couldn't parse the 227-line the server sent.
-	15 FTP can't get host. Couldn't resolve the host IP we got in the 227-line.
-	17 FTP couldn't set binary. Couldn't change transfer method to binary.
-	18 Partial file. Only a part of the file was transferred.
-	19 FTP couldn't download/access the given file, the RETR (or similar) command failed.
-	21 FTP quote error. A quote command returned error from the server.
-	22 HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f, --fail is used.
-	23 Write error. Curl couldn't write data to a local filesystem or similar.
-	25 FTP couldn't STOR file. The server denied the STOR operation, used for FTP uploading.
-	26 Read error. Various reading problems.
-	27 Out of memory. A memory allocation request failed.
-	28 Operation timeout. The specified time-out period was reached according to the condi‐ tions.
-	30 FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!
-	31 FTP couldn't use REST. The REST command failed. This command is used for resumed FTP transfers.
-	33 HTTP range error. The range "command" didn't work.
-	34 HTTP post error. Internal post-request generation error.
-	35 SSL connect error. The SSL handshaking failed.
-	36 FTP bad download resume. Couldn't continue an earlier aborted download.
-	37 FILE couldn't read file. Failed to open the file. Permissions?
-	38 LDAP cannot bind. LDAP bind operation failed.
-	39 LDAP search failed.
-	41 Function not found. A required LDAP function was not found.
-	42 Aborted by callback. An application told curl to abort the operation.
-	43 Internal error. A function was called with a bad parameter.
-	45 Interface error. A specified outgoing interface could not be used.
-	47 Too many redirects. When following redirects, curl hit the maximum amount.
-	48 Unknown option specified to libcurl. This indicates that you passed a weird option to curl that was passed on to libcurl and rejected. Read up in the manual!
-	49 Malformed telnet option.
-	51 The peer's SSL certificate or SSH MD5 fingerprint was not OK.
-	52 The server didn't reply anything, which here is considered an error.
-	53 SSL crypto engine not found.
-	54 Cannot set SSL crypto engine as default.
-	55 Failed sending network data.
-	56 Failure in receiving network data.
-	58 Problem with the local certificate.
-	59 Couldn't use specified SSL cipher.
-	60 Peer certificate cannot be authenticated with known CA certificates.
-	61 Unrecognized transfer encoding.
-	62 Invalid LDAP URL.
-	63 Maximum file size exceeded.
-	64 Requested FTP SSL level failed.
-	65 Sending the data requires a rewind that failed.
-	66 Failed to initialise SSL Engine.
-	67 The user name, password, or similar was not accepted and curl failed to log in.
-	68 File not found on TFTP server.
-	69 Permission problem on TFTP server.
-	70 Out of disk space on TFTP server.
-	71 Illegal TFTP operation.
-	72 Unknown TFTP transfer ID.
-	73 File already exists (TFTP).
-	74 No such user (TFTP).
-	75 Character conversion failed.
-	76 Character conversion functions required.
-	77 Problem with reading the SSL CA cert (path? access rights?).
-	78 The resource referenced in the URL does not exist.
-	79 An unspecified error occurred during the SSH session.
-	80 Failed to shut down the SSL connection.
-	82 Could not load CRL file, missing or wrong format (added in 7.19.0).
-	83 Issuer check failed (added in 7.19.0).
-	84 The FTP PRET command failed
-	85 RTSP: mismatch of CSeq numbers
-	86 RTSP: mismatch of Session Identifiers
-	87 unable to parse FTP file list
-	88 FTP chunk callback reported error
-	127 Unknown error
+    fi
+    codes=$(cat <<-'EOF'
+    1 Unsupported protocol. This build of curl has no support for this protocol.
+    2 Failed to initialize.
+    3 URL malformed. The syntax was not correct.
+    4 A feature or option that was needed to perform the desired request was not enabled or was explicitly disabled at build-time. To make curl able to do this, you probably need another build of libcurl!
+    5 Couldn't resolve proxy. The given proxy host could not be resolved.
+    6 Couldn't resolve host. The given remote host was not resolved.
+    7 Failed to connect to host.
+    8 FTP weird server reply. The server sent data curl couldn't parse.
+    9 FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried to change to a directory that doesn't exist on the server.
+    11 FTP weird PASS reply. Curl couldn't parse the reply sent to the PASS request.
+    13 FTP weird PASV reply, Curl couldn't parse the reply sent to the PASV request.
+    14 FTP weird 227 format. Curl couldn't parse the 227-line the server sent.
+    15 FTP can't get host. Couldn't resolve the host IP we got in the 227-line.
+    17 FTP couldn't set binary. Couldn't change transfer method to binary.
+    18 Partial file. Only a part of the file was transferred.
+    19 FTP couldn't download/access the given file, the RETR (or similar) command failed.
+    21 FTP quote error. A quote command returned error from the server.
+    22 HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f, --fail is used.
+    23 Write error. Curl couldn't write data to a local filesystem or similar.
+    25 FTP couldn't STOR file. The server denied the STOR operation, used for FTP uploading.
+    26 Read error. Various reading problems.
+    27 Out of memory. A memory allocation request failed.
+    28 Operation timeout. The specified time-out period was reached according to the condi‐ tions.
+    30 FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!
+    31 FTP couldn't use REST. The REST command failed. This command is used for resumed FTP transfers.
+    33 HTTP range error. The range "command" didn't work.
+    34 HTTP post error. Internal post-request generation error.
+    35 SSL connect error. The SSL handshaking failed.
+    36 FTP bad download resume. Couldn't continue an earlier aborted download.
+    37 FILE couldn't read file. Failed to open the file. Permissions?
+    38 LDAP cannot bind. LDAP bind operation failed.
+    39 LDAP search failed.
+    41 Function not found. A required LDAP function was not found.
+    42 Aborted by callback. An application told curl to abort the operation.
+    43 Internal error. A function was called with a bad parameter.
+    45 Interface error. A specified outgoing interface could not be used.
+    47 Too many redirects. When following redirects, curl hit the maximum amount.
+    48 Unknown option specified to libcurl. This indicates that you passed a weird option to curl that was passed on to libcurl and rejected. Read up in the manual!
+    49 Malformed telnet option.
+    51 The peer's SSL certificate or SSH MD5 fingerprint was not OK.
+    52 The server didn't reply anything, which here is considered an error.
+    53 SSL crypto engine not found.
+    54 Cannot set SSL crypto engine as default.
+    55 Failed sending network data.
+    56 Failure in receiving network data.
+    58 Problem with the local certificate.
+    59 Couldn't use specified SSL cipher.
+    60 Peer certificate cannot be authenticated with known CA certificates.
+    61 Unrecognized transfer encoding.
+    62 Invalid LDAP URL.
+    63 Maximum file size exceeded.
+    64 Requested FTP SSL level failed.
+    65 Sending the data requires a rewind that failed.
+    66 Failed to initialise SSL Engine.
+    67 The user name, password, or similar was not accepted and curl failed to log in.
+    68 File not found on TFTP server.
+    69 Permission problem on TFTP server.
+    70 Out of disk space on TFTP server.
+    71 Illegal TFTP operation.
+    72 Unknown TFTP transfer ID.
+    73 File already exists (TFTP).
+    74 No such user (TFTP).
+    75 Character conversion failed.
+    76 Character conversion functions required.
+    77 Problem with reading the SSL CA cert (path? access rights?).
+    78 The resource referenced in the URL does not exist.
+    79 An unspecified error occurred during the SSH session.
+    80 Failed to shut down the SSL connection.
+    82 Could not load CRL file, missing or wrong format (added in 7.19.0).
+    83 Issuer check failed (added in 7.19.0).
+    84 The FTP PRET command failed
+    85 RTSP: mismatch of CSeq numbers
+    86 RTSP: mismatch of Session Identifiers
+    87 unable to parse FTP file list
+    88 FTP chunk callback reported error
+    127 Unknown error
         '
-	EOF
-	)
-    msg=`echo "$codes"|sed -r 's#^[ \t]+##'|grep "^$1 "|cut -f2- -d ' '`
-    if [ -z "$msg" ]
+EOF
+    )
+    msg=$(echo "${codes}" | sed -r 's#^[ \t]+##' | grep "^${1} " \
+        | cut -f2- -d ' ')
+    if [ -z "${msg}" ]
     then
         msg="Unknown code"
     fi
-    echo "CURL ERROR $1: ${msg}" >&2
-    exit $EXITCODE
+    echo "CURL ERROR ${1}: ${msg}" >&2
+    exit ${EXITCODE}
 }
 
 _httpcode()
 {
-	if [ -z "$1" -o "$1" = "200" ]
-	then
+    if [ -z "${1}" -o "${1}" = "200" ]
+    then
             exit 0
-	fi
-	codes=$(cat <<-'EOF'
-	301 Resource has been moved permanently
-	302 Resource has been moved temporarily
+    fi
+    codes=$(cat <<-'EOF'
+    301 Resource has been moved permanently
+    302 Resource has been moved temporarily
     400 HTTP Bad request
     401 Unauthorized properly: please check supplied username and password
     403 Forbidden resource: please check permissions
@@ -197,14 +198,15 @@ _httpcode()
     501 Internal CQ error
     502 Internal CQ error
     503 Internal CQ error
-	EOF
-	)
-    msg=`echo "$codes"|sed -r 's#^[ \t]+##'|grep "^$1 "|cut -f2- -d ' '`
-    if [ -z "$msg" ]
+EOF
+    )
+    msg=$(echo "${codes}" | sed -r 's#^[ \t]+##' | grep "^${1} " \
+        | cut -f2- -d ' ')
+    if [ -z "${msg}" ]
     then
         msg="Unknown response"
     fi
-    echo "HTTP RESPONSE $1: ${msg}" >&2
+    echo "HTTP RESPONSE ${1}: ${msg}" >&2
     exit 1
 }
 
@@ -217,32 +219,32 @@ _java_exception()
 
 _java_exception_detection()
 {
-    grep -Ec "(^[\.[:alnum:]]+Exception:.*$|^[[:space:]]+at[[:space:]][\.\
+    grep -Ec "(^[\.[:alnum:]]+Exception:.*\$|^[[:space:]]+at[[:space:]][\.\
         [:alnum:]]+(\(.+\))?)"
     exit
 }
 
 _parse()
 {
-    ECHO=`which echo`
-    $ECHO -e "$1\t$2\t$3\t$4\t$5"
+    ECHO=$(which echo)
+    ${ECHO} -e "${1}\t${2}\t${3}\t${4}\t${5}"
     exit
 }
 
 _invalid_option()
 {
-    if [ $1 -ne 1 ]
+    if [ "${1}" -ne 1 ]
     then
-       echo "Invalid option: -$2" >&2
+       echo "Invalid option: -${2}" >&2
       _usage
     fi
 }
 
 _missing_argument()
 {
-    if [ $1 -eq 0 ]
+    if [ "${1}" -eq 0 ]
     then
-      echo "Option -$2 requires an argument." >&2
+      echo "Option -${2} requires an argument." >&2
       _usage
     fi
 }
@@ -269,55 +271,63 @@ argument=?
 
 while getopts "${OPTIONS}" option
 do
-    mode=$option
-    case $option in
+    mode=${option}
+    case ${option} in
         P) parse_mode=1; OPTIONS=":P${PARSE_OPTIONS}";;
-        u) username=$OPTARG; explicit_option=1;;
-        p) password=$OPTARG; explicit_option=1;;
-        i) instance=`echo "$OPTARG"|sed -r 's#[/]+$##'`; explicit_option=1;;
-        C) argument=$OPTARG;;
-        H) argument=$OPTARG;;
-        \?) _invalid_option $parse_mode $OPTARG;;
-        :) _missing_argument $parse_mode $OPTARG;;
+        u) username=${OPTARG}; explicit_option=1;;
+        p) password=${OPTARG}; explicit_option=1;;
+        i) instance=$(echo "${OPTARG}" | sed -r 's#[/]+$##'); 
+           explicit_option=1;;
+        C) argument=${OPTARG};;
+        H) argument=${OPTARG};;
+        \?) _invalid_option ${parse_mode} "${OPTARG}";;
+        :) _missing_argument ${parse_mode} "${OPTARG}";;
     esac
 
     continue=1
-    last_optind=$OPTIND
+    last_optind=${OPTIND}
     total_shift=0
     delta=0
-    while [ $continue -eq 1 ]; do
-        optind_before=$OPTIND
+    while [ ${continue} -eq 1 ]; do
+        optind_before=${OPTIND}
         getopts "${OPTIONS}" vopt
-        getopts_status=$?
+        getopts_status=${?}
         total_shift=$((total_shift+delta))
         delta=$((OPTIND-optind_before))
 
-        if [ $getopts_status -ne 0 ]; then
-            if [ $# -le $OPTIND ]; then
+        if [ ${getopts_status} -ne 0 ]
+        then
+            if [ ${#} -le ${OPTIND} ]
+            then
                 # Parse break - EOL reached
                 continue=0
-            elif [ $delta -ge 0 ]; then
+            elif [ ${delta} -ge 0 ]
+            then
                 # Skip broken argument
                 OPTIND=$((OPTIND+1))
                 continue=1
             fi
-        elif [ "$vopt" = "?" -o "$vopt" = ":" ]; then
+        elif [ "${vopt}" = "?" -o "${vopt}" = ":" ]
+        then
             # Invalid option - continue readahed
             continue=1
         else
             # Valid option - calculate shift
             continue=0
             valid_option_shift=$((optind_before-last_optind))
-            if [ $valid_option_shift -ge 0  ]; then
-                total_shift=$valid_option_shift
+            if [ $valid_option_shift -ge 0  ]
+            then
+                total_shift=${valid_option_shift}
             fi
         fi
     done
 
     OPTIND=$((last_optind+total_shift))
     # Check for infinitive parsing of the same argument twice by getopts
-    if [ $OPTIND -eq $last_optind ]; then
-        if [ $idle_pass -gt 2 ]; then
+    if [ $OPTIND -eq ${last_optind} ]
+    then
+        if [ ${idle_pass} -gt 2 ]
+        then
             # Skip in case of infinitive loop
             OPTIND=$((OPTIND+1))
         fi
@@ -331,22 +341,22 @@ done
 shift $((OPTIND-1))
 
 # cqapi Parse mode for -u -p -i parameters
-if [ $parse_mode -eq 1 ]
+if [ ${parse_mode} -eq 1 ]
 then
-    _parse $username $password $instance $explicit_option $PARSE_OPTIONS
+    _parse "${username}" "${password}" "${instance}" "${explicit_option}" \
+        "${PARSE_OPTIONS}"
     exit 0
 fi
 
 # cqapi normal modes
-case $mode in
+case "${mode}" in
   c) _curlpath;;
-  C) _curlcode $argument;;
-  H) _httpcode $argument;;
+  C) _curlcode "${argument}";;
+  H) _httpcode "${argument}";;
   E) _java_exception;;
   e) _java_exception_detection;;
   v) _version;;
 esac
 
 _usage
-
 
diff --git a/cqchk b/cqchk
--- a/cqchk
+++ b/cqchk
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 Invoke CRX repository check and fix on them. By default fixes are not performed.  
 Read-only access to repositorys is used unless -f option is provided.  
 
@@ -38,114 +38,113 @@ EOT
 exit 1
 }
 
-CWD=`dirname "${0}"`
+CWD=$(dirname "${0}")
 API="$CWD/cqapi"
-APITEST=`"${API}" -P`
+"${API}" -P >/dev/null
 if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
+CURLBIN=$("${API}" -c)
 if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
-
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 fix=false
 while getopts ":f${apigetopts}" opt; do
-  case $opt in
-     f)  
-      fix=true;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+    case $opt in
+        f)  
+            fix=true;;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ $# -ge 1 -o $passed -eq 0 ];
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ]
 then
-	_usage
+    _usage
 fi
 
-
-echo -n "Starting repository traversal check..."
-REFERER="$instance/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
-AUTH="$username:$password"
+ECHON=$(which echo)
+[ ${?} -ne 0 -o -z "${ECHON}" ] && ECHON="echo" || ECHON="${ECHON} -n "
+${ECHON} "Starting repository traversal check..."
+REFERER="${instance}/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
+AUTH="${username}:${password}"
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/traversa\
 lCheck/java.lang.String%2Cjava.lang.Boolean%2Cjava.lang.Boolean"
-REFERERHEADER="Referer: $REFERER"
+REFERERHEADER="Referer: ${REFERER}"
 
 
-STATUS=`$CURLBIN \
-	-s \
-        --write-out "%{http_code}" \
-	-u "$AUTH" \
-	-H "$REFERERHEADER" \
-	-X POST --data "logEach=false&fixInconsistencies=${fix}" \
-	"$instance${FILEPATH}"`
+STATUS=$(${CURLBIN} \
+    -s \
+    --write-out "%{http_code}" \
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
+    -X POST --data "logEach=false&fixInconsistencies=${fix}" \
+    "${instance}${FILEPATH}")
 
 EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Cannot invoke repository traversal check." >&2
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;'`
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+STATUS=$(echo "${STATUS}" | sed '$d;')
 echo "${STATUS}"
-"${API}" -H $STATUSCODE
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Cannot invoke repository traversal check." >&2
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
 
 
-echo -n "Starting repository consistency check..."
+${ECHON} "Starting repository consistency check..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/consiste\
 ncyCheck/java.lang.String%2Cjava.lang.Boolean"
-STATUS=`$CURLBIN \
-	-s \
-        --write-out "%{http_code}" \
-	-u "$AUTH" \
-	-H "$REFERERHEADER" \
-	-X POST --data "fixInconsistencies=${fix}" \
-	"$instance${FILEPATH}" `
+STATUS=$(${CURLBIN} \
+    -s \
+    --write-out "%{http_code}" \
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
+    -X POST --data "fixInconsistencies=${fix}" \
+    "${instance}${FILEPATH}")
 EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Cannot invoke repository consistency check." >&2
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;'`
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+STATUS=$(echo "${STATUS}" | sed '$d;')
 echo "${STATUS}"
-"${API}" -H $STATUSCODE
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Cannot invoke repository consistency check." >&2
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
-
 
diff --git a/cqclr b/cqclr
--- a/cqclr
+++ b/cqclr
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 Clear cache for specified dispatcher (-i option). By default clear the whole
 cache / node or specified node provided by -r option. To match specific
 dispatcher flush cache server configuration use -v domain option to request
@@ -50,50 +50,51 @@ EOT
 exit 1
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
 if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
-if [ $? -ne 0 ]
+CURLBIN=$("${API}" -c)
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
 
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 path="/"
 vhost=""
-while getopts ":r:v:${apigetopts}" opt; do
-  case ${opt} in
-     r)
-      path="${OPTARG}";;
-     v)
-      vhost="${OPTARG}";;
-    \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+while getopts ":r:v:${apigetopts}" opt
+do
+    case ${opt} in
+        r)
+            path="${OPTARG}";;
+        v)
+            vhost="${OPTARG}";;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ ${#} -ge 1 -o ${passed} -eq 0 ]
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ]
 then
-	_usage
+    _usage
 fi
 
 
@@ -102,11 +103,10 @@ REFERER=${URL}
 AUTH="${username}:${password}"
 REFERERHEADER="Referer: ${REFERER}"
 VHOSTHEADER=""
-VHOSTOPTION=""
 echo "Clearing dispatcher cache:"
 echo "                     path: ${path}"
 
-if [ "$vhost" != "" ]
+if [ "${vhost}" != "" ]
 then
     VHOSTHEADER="Host: ${vhost}"
     echo "           requested host: ${vhost}"
@@ -115,7 +115,7 @@ fi
 echo "           connection URL: ${instance}"
 echo ""
 
-STATUS=`$CURLBIN -s -X POST \
+STATUS=$(${CURLBIN} -s -X POST \
         --output /dev/null \
         --write-out %{http_code} \
         -u "${AUTH}" \
@@ -123,14 +123,15 @@ STATUS=`$CURLBIN -s -X POST \
         -H "CQ-Handle: ${path}" \
         -H "Content-Length: 0" \
         -H "${VHOSTHEADER}" \
-        "${URL}"`
+        -H "${REFERERHEADER}" \
+        "${URL}")
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
 if [ ${EXITCODE} -ne 0 ]
 then
     exit ${EXITCODE}
 fi
-"${API}" -H ${STATUS}
+"${API}" -H "${STATUS}"
 EXITCODE=${?}
 if [ ${EXITCODE} -ne 0 ]
 then
diff --git a/cqcp b/cqcp
--- a/cqcp
+++ b/cqcp
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...] package-resource-name
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...] package-resource-name
 Makes local copy of already uploaded package by group id and name in CQ Package
 Manager using instance URL.
  
@@ -41,128 +41,133 @@ EOT
 exit 1
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
+CURLBIN=$("${API}" -c)
 if [ $? -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
-
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":o:g:${apigetopts}" opt; do
-  case $opt in
-     g)  
-      group="$OPTARG";;
-     o)  
-      outfile="$OPTARG";;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+while getopts ":o:g:${apigetopts}" opt
+do
+    case ${opt} in
+        g)  
+            group="${OPTARG}";;
+        o)  
+            outfile="${OPTARG}";;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ $# -ne 1 -o $passed -eq 0 ];
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ];
 then
-	_usage
+    _usage
 fi
-name=$1
+name=${1}
 
 if [ -z  "${group}" ]
 then
-        group_arg=""
+    group_switch=""
+    group_arg=""
 else
-        group_arg="-F \"group=${group}\""
+    group_switch="-F"
+    group_arg="group=${group}"
 fi
 
-if [ -z "$outfile" ]
+if [ -z "${outfile}" ]
 then
-        outfile="${name}.zip"
+    outfile="${name}.zip"
 fi
-redirection="-o \"$outfile\""
+redirection="${outfile}"
 
-REFERER="$instance/etc/packages"
-AUTH="$username:$password"
+REFERER="${instance}/etc/packages"
+AUTH="${username}:${password}"
 FILEPATH="/crx/packmgr/service.jsp"
-REFERERHEADER="Referer: $REFERER"
+REFERERHEADER="Referer: ${REFERER}"
 
-STATUS=`$CURLBIN \
+STATUS=$($CURLBIN \
     -s \
     --write-out "%{content_type} %{http_code}" \
-    -u "$AUTH" \
-    -H "$REFERERHEADER" \
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
     -F cmd=get \
-    ${group_arg} \
+    ${group_switch} "${group_arg}" \
     -o /dev/null \
     -F "name=${name}" \
-    "${instance}${FILEPATH}"`
-EXITCODE=$?
-"${API}" -C $EXITCODE
-STATUSFIELDS=`echo "$STATUS"|tail -n 1`
-STATUSCODE=`echo "$STATUSFIELDS"|cut -f2 -d ' '`
-CONTENTTYPE=`echo "$STATUSFIELDS"|cut -f1 -d ' '`
-"${API}" -H ${STATUSCODE}
+    "${instance}${FILEPATH}")
+
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+STATUSFIELDS=$(echo "${STATUS}" | tail -n 1)
+STATUSCODE=$(echo "${STATUSFIELDS}" | cut -f2 -d ' ')
+CONTENTTYPE=$(echo "${STATUSFIELDS}" | cut -f1 -d ' ')
+"${API}" -H "${STATUSCODE}"
 EXITCODE2=$?
-fullfile=`readlink -f $outfile`
+fullfile=$(readlink -f "${outfile}")
 plain=0
 if [ "${EXITCODE2}" -eq 0 -a ${EXITCODE} -eq 0 ]
 then
-    plain=`echo "$CONTENTTYPE"|grep -c 'plain'`
+    plain=$(echo "${CONTENTTYPE}" | grep -c 'plain')
 fi
+
 EXITCODE=$((EXITCODE + EXITCODE2))
-if [ $EXITCODE -ne 0 ]
+if [ ${EXITCODE} -ne 0 ]
 then
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-if [ $plain -eq 1 ]
+if [ "${plain}" -eq 1 ]
 then
-    redirection="-o -"
+    redirection="-"
 fi
 
-STATUS=`$CURLBIN \
+STATUS=$(${CURLBIN} \
     -s \
     --write-out "%{http_code}" \
-    -u "$AUTH" \
-    -H "$REFERERHEADER" \
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
     -F cmd=get \
-    ${group_arg} \
-    -F name=${name} \
-    ${redirection} \
-    "${instance}${FILEPATH}"`
-EXITCODE=$?
-"${API}" -C $EXITCODE
-STATUSCODE=`echo "$STATUS"|tail -n 1|cut -f1 -d ' '`
-CONTENTTYPE=`echo "$STATUS"|tail -n 1|cut -f2 -d ' '`
-STATUS=`echo "$STATUS"|sed '$d'`
-"${API}" -H ${STATUSCODE}
+    ${group_switch} "${group_arg}" \
+    -F "name=${name}" \
+    -o "${redirection}" \
+    "${instance}${FILEPATH}")
+
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+STATUSCODE=$(echo "${STATUS}" | tail -n 1 | cut -f1 -d ' ')
+CONTENTTYPE=$(echo "${STATUS}" | tail -n 1 | cut -f2 -d ' ')
+STATUS=$(echo "$STATUS" | sed '$d')
+"${API}" -H "${STATUSCODE}"
 EXITCODE2=$?
 if [ ${EXITCODE2} -eq 0 -a ${EXITCODE} -eq 0 ]
 then
-    if [ $plain -eq 0 ]
+    if [ "${plain}" -eq 0 ]
     then
-        echo "Package copied to: $fullfile"
+        echo "Package copied to: '${fullfile}'"
     else
-        echo "$STATUS"
+        echo "${STATUS}"
     fi
 fi
 exit $((EXITCODE + EXITCODE2))
diff --git a/cqls b/cqls
--- a/cqls
+++ b/cqls
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 List all packages in CQ Package Manager using instance URL.
 
 Examples:
@@ -44,9 +44,9 @@ exit 1
 _print_preformatted()
 {
     SEP='|'
-    ECHO=`which echo`
+    ECHO=$(which echo)
     [ ${?} -ne 0 -o -z "${ECHO}" ] && ECHO="echo" || ECHO="${ECHO} -e "
-    TAB=`$ECHO "\t"`
+    TAB=$(${ECHO} "\t")
     STATUS=${1}
     mode=${2}
     machine=${3}
@@ -99,29 +99,30 @@ _print_preformatted()
     REGEXP2="(.*)${G2}${G3}${G4}${G5}${G6}${G7}.*"
     ORDERING2="\1\2\t\3\t\4\t\5\t\6\t\7"
 
-    filtered_items=`${ECHO} -e "${STATUS}" | tr -d '\n' | \
+    filtered_items=$(${ECHO} -e "${STATUS}" | tr -d '\n' | \
         sed 's/<package>/\n<package>/g' | \
-        sed -r 's/>\s+</></g' | grep -E "${REGEXP1}"`
-    items=`${ECHO} -e "${filtered_items}" | sed -E "s#${REGEXP1}#${ORDERING1}#"\
+        sed -r 's/>\s+</></g' | grep -E "${REGEXP1}")
+    items=$(${ECHO} -e "${filtered_items}" \
+        | sed -E "s#${REGEXP1}#${ORDERING1}#" \
         | sed -E "s#${REGEXP2}#${ORDERING2}#" | sort -nk1 -t "${TAB}" \
-        | cut -f1-${fields_num}`
-    total=`${ECHO} -e "${items}" | wc -l`
-    if [ ${machine} -eq 0 ]
+        | cut -f1-${fields_num})
+    total=$(${ECHO} -e "${items}" | wc -l)
+    if [ "${machine}" -eq 0 ]
     then
         ${ECHO} "${total} packages."
         ${ECHO} ""
         H1="NAME|GROUP|VERSION|SIZE|DOWNLOAD_NAME"
         H2="|CREATED|CREATED_BY|MODIFIED|MODIFIED_BV|INSTALLED|INSTALLED_BY"
         header="${H1}${H2}"
-        output=`${ECHO} -e "${header}" | cut -f1-${fields_num} -d '|'`
+        output=$(${ECHO} -e "${header}" | cut -f1-${fields_num} -d '|')
         output="${output}\n"
     fi
     output="${output}${items}"
-    if [ ${machine} -eq 1 ]
+    if [ "${machine}" -eq 1 ]
     then
         ${ECHO} -n "${output}"
     else
-        COLUMN=`which column`
+        COLUMN=$(which column)
         if [ ${?} -ne 0 -o -z "${COLUMN}" ]
         then
             ${ECHO} "Cannot find column utility"
@@ -132,30 +133,30 @@ _print_preformatted()
     fi
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
-if [ $? -ne 0 ]
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
-if [ $? -ne 0 ]
+CURLBIN=$("${API}" -c)
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
 
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 listing_long=0
@@ -163,23 +164,24 @@ listing_names=0
 listing_machine=0
 listing_mode=2
 listing_original=0
-while getopts ":l1mx${apigetopts}" opt; do
-  case $opt in
-    l)
-      listing_long=1
-      listing_mode=3;;
-    1)
-      listing_names=1
-      listing_mode=1;;
-    m)
-      listing_machine=1;;
-    x)
-      listing_original=1;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+while getopts ":l1mx${apigetopts}" opt
+do
+    case ${opt} in
+        l)
+            listing_long=1
+            listing_mode=3;;
+        1)
+            listing_names=1
+            listing_mode=1;;
+        m)
+            listing_machine=1;;
+        x)
+            listing_original=1;;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
@@ -197,48 +199,47 @@ then
     _usage
 fi
 
-if [ $# -gt 0 -o $passed -eq 0 ];
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ];
 then
-	_usage
+    _usage
 fi
 
-
-REFERER="$instance/crx/packmgr"
-AUTH="$username:$password"
+REFERER="${instance}/crx/packmgr"
+AUTH="${username}:${password}"
 FILEPATH="/crx/packmgr/service.jsp"
-REFERERHEADER="Referer: $REFERER"
+REFERERHEADER="Referer: ${REFERER}"
 
-STATUS=`$CURLBIN \
-	-s \
+STATUS=$(${CURLBIN} \
+    -s \
     --write-out "%{http_code}" \
-	-u "$AUTH" \
-	-H "$REFERERHEADER" \
-        -F cmd=ls \
-	"$instance${FILEPATH}"`
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
+    -F cmd=ls \
+    "${instance}${FILEPATH}")
 
-EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Couldn't get packages list"
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-"${API}" -H ${STATUSCODE}
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Couldn't get packages list"
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
 
-STATUS=`echo "$STATUS"|sed '$d'`
-if [ $listing_original -eq 1 ]
+STATUS=$(echo "${STATUS}" | sed '$d')
+if [ ${listing_original} -eq 1 ]
 then
     echo "${STATUS}"
 else
-    _print_preformatted "${STATUS}" $listing_mode $listing_machine
+    _print_preformatted "${STATUS}" ${listing_mode} ${listing_machine}
 fi
 exit 0
 
diff --git a/cqosgi b/cqosgi
--- a/cqosgi
+++ b/cqosgi
@@ -16,7 +16,7 @@
 _usage()
 {
     cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+Usage: $(basename "${0}") [OPTION...]
 Returns CQ instance OSGI bundles list and its states in pretty-printed form
 using instance URL. Use -j to return original JSON form. Use -m for machine.
 Run (start) or stop specified bundles using -r or -s options.
@@ -54,32 +54,32 @@ exit 1
 _print_preformatted()
 {
     SEP='|'
-    ECHO=`which echo`
+    ECHO=$(which echo)
     [ ${?} -ne 0 -o -z "${ECHO}" ] && ECHO="echo" || ECHO="${ECHO} -e "
-    TAB=`${ECHO} "\t"`
+    TAB=$(${ECHO} "\t")
     STATUS=${1}
     machine_friendly=${2}
     REGEXP=".*\"id\":([0-9]+),\"name\":\"([^\"]+)\",\"fragment\":([A-Za-z]+).*,\
 \"stateRaw\":[0-9]+,\"state\":\"([A-Za-z ]+)\",\"version\":\"([^\"]+)\",\"\
 symbolicName\":\"([^\"]+)\",\"category\":\"([^\"]*)\".*"
-    filtered_items=`${ECHO} -e "${STATUS}" | sed 's#{#\n{#g' \
-        | grep -E "${REGEXP}"`
-    items=`${ECHO} -e "${filtered_items}" | \
-        sed -E "s#${REGEXP}#\1\t\6\t\4\t\5\t\2#"\
-        | sort -nk1 -t "${TAB}"`
-    total=`${ECHO} -e "${items}" | wc -l`
-    if [ ${machine_friendly} -eq 0 ]
+    filtered_items=$(${ECHO} -e "${STATUS}" | sed 's#{#\n{#g' \
+        | grep -E "${REGEXP}")
+    items=$(${ECHO} -e "${filtered_items}" \
+        | sed -E "s#${REGEXP}#\1\t\6\t\4\t\5\t\2#"\
+        | sort -nk1 -t "${TAB}")
+    total=$(${ECHO} -e "${items}" | wc -l)
+    if [ "${machine_friendly}" -eq 0 ]
     then
         ${ECHO} "${total} bundles."
         ${ECHO} ""
         output="ID|SYMBOL|STATUS|VERSION|NAME\n"
     fi
     output="${output}${items}"
-    if [ ${machine_friendly} -eq 1 ]
+    if [ "${machine_friendly}" -eq 1 ]
     then
         ${ECHO} "${output}"
     else
-        COLUMN=`which column`
+        COLUMN=$(which column)
         if [ ${?} -ne 0 -o -z "${COLUMN}" ]
         then
             echo "Cannot find column utility"
@@ -89,9 +89,9 @@ symbolicName\":\"([^\"]+)\",\"category\":\"([^\"]*)\".*"
     fi
 }
 
-CWD=`dirname "${0}"`
+CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
-APITEST=`"${API}" -P`
+"${API}" -P >/dev/null
 
 if [ ${?} -ne 0 ]
 then
@@ -99,7 +99,7 @@ then
     exit 1
 fi
 
-CURLBIN=`"${API}" -c`
+CURLBIN=$("${API}" -c)
 if [ ${?} -ne 0 ]
 then
     echo "Fatal: cannot find curl" >&2
@@ -108,36 +108,37 @@ fi
 
 
 # API common options
-cmdapi=`    "${API}" -P ${@}`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 pretty=1
 machine_friendly=0
 operations=""
-while getopts ":jmr:s:${apigetopts}" opt; do
-  case $opt in
-     j)
-      pretty=0;;
-     m)
-      machine_friendly=1;;
-     r)
-      operations="${operations} R${OPTARG}";;
-     s)
-      operations="${operations} S${OPTARG}";;
-     \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+while getopts ":jmr:s:${apigetopts}" opt
+do
+    case ${opt} in
+        j)
+            pretty=0;;
+        m)
+            machine_friendly=1;;
+        r)
+            operations="${operations} R${OPTARG}";;
+        s)
+            operations="${operations} S${OPTARG}";;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ ${#} -gt 0 -o ${passed} -eq 0 ]
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ]
 then
     _usage
 fi
@@ -148,17 +149,24 @@ then
     _usage
 fi
 
+if [ "${operations}" != "" -a \( ${pretty} -eq 0 -o ${machine_friendly} -eq 1 \) ]
+then
+    echo "View options -m or -j cannot be applied together with operations:" \
+        "-r/-s" >&2
+    exit 2
+fi
+
 FILEPATH="/system/console/bundles/.json"
 REFERER="${instance}${FILEPATH}"
 AUTH="${username}:${password}"
 REFERERHEADER="Referer: ${REFERER}"
 
-STATUS=`${CURLBIN} \
+STATUS=$(${CURLBIN} \
     -s \
     --write-out "%{http_code}" \
     -u "${AUTH}" \
     -H "${REFERERHEADER}" \
-    "${instance}${FILEPATH}"`
+    "${instance}${FILEPATH}")
 
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
@@ -166,36 +174,32 @@ if [ ${EXITCODE} -ne 0 ]
 then
     exit ${EXITCODE}
 fi
-STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-"${API}" -H ${STATUSCODE}
-EXITCODE2=$?
+STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
 if [ ${EXITCODE2} -ne 0 ]
 then
     exit ${EXITCODE2}
 fi
-STATUS=`echo "${STATUS}"|sed -r 's#[0-9]{3}$##'`
 
-if [ "${operations}" != "" -a \( ${pretty} -eq 0 -o ${machine_friendly} -eq 1 \) ]
-then
-    echo "View options -m or -j cannot be applied together with operations: -r/-s" >&2
-    exit 2
-fi
+STATUS=$(echo "${STATUS}" | sed -r 's#[0-9]{3}$##')
 
 if [ "${operations}" != "" ]
 then
-    bundle_map=`_print_preformatted "${STATUS}" 1 | cut -f 1,2`
+    bundle_map=$(_print_preformatted "${STATUS}" 1 | cut -f 1,2)
     operations_by_id=""
     for operation in ${operations}
     do
-        action=`echo "${operation}" | cut -c1`
-        bundle=`echo "${operation}" | cut -c2-`
+        action=$(echo "${operation}" | cut -c1)
+        bundle=$(echo "${operation}" | cut -c2-)
         if [ "${action}" != "R" -a "${action}" != "S" ]
         then
             echo "Only run/stop operations are permitted for bundles" >&2
             exit 2
         fi
-        bundle_escaped=`echo "${bundle}" | sed -r 's#\.#\\.#g' `
-        id=`echo "$bundle_map" | grep -E "[[:space:]]+${bundle_escaped}$" | cut -f1`
+        bundle_escaped=$(echo "${bundle}" | sed -r 's#\.#\\.#g')
+        id=$(echo "$bundle_map" | grep -E "[[:space:]]+${bundle_escaped}\$" \
+            | cut -f1)
         if [ "$id" = "" ]
         then
             echo "Cannot find specified bundle: ${bundle}" >&2
@@ -206,10 +210,10 @@ then
     done
     for op in ${operations_by_id}
     do
-        action=` echo "${op}" | cut -c1 `
-        bundle_spec=` echo "${op}" | cut -c2- `
-        bundle_id=` echo "${bundle_spec}" | sed -r 's/^([0-9]+).+$/\1/' `
-        bundle=` echo "${bundle_spec}" | sed -r 's/^[0-9]+(.+)$/\1/' `
+        action=$(echo "${op}" | cut -c1)
+        bundle_spec=$(echo "${op}" | cut -c2-)
+        bundle_id=$(echo "${bundle_spec}" | sed -r 's/^([0-9]+).+$/\1/')
+        bundle=$(echo "${bundle_spec}" | sed -r 's/^[0-9]+(.+)$/\1/')
 
         [ "${action}" = "R" ] && activity="Running bundle: " \
             || activity="Stopping bunle: "
@@ -218,13 +222,13 @@ then
         post_param="action=${optype}"
 
         echo "${activity}${bundle} (#${bundle_id})"
-        STATUS=`${CURLBIN} \
-                -s \
-                --write-out "%{http_code}" \
-                -u "${AUTH}" \
-                -H "${REFERERHEADER}" \
-                -d "${post_param}" \
-                "${instance}${FILEPATH}/${bundle_id}"`
+        STATUS=$(${CURLBIN} \
+            -s \
+            --write-out "%{http_code}" \
+            -u "${AUTH}" \
+            -H "${REFERERHEADER}" \
+            -d "${post_param}" \
+            "${instance}${FILEPATH}/${bundle_id}")
 
         EXITCODE=${?}
         "${API}" -C ${EXITCODE}
@@ -232,8 +236,8 @@ then
         then
             exit ${EXITCODE}
         fi
-        STATUSCODE=`echo "${STATUS}"|grep -o -E '[0-9]{3}'|tail -n 1`
-        "${API}" -H ${STATUSCODE}
+        STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
+        "${API}" -H "${STATUSCODE}"
         EXITCODE2=${?}
         if [ ${EXITCODE2} -ne 0 ]
         then
@@ -245,7 +249,7 @@ fi
 
 if [ ${pretty} -eq 1 ]
 then
-    _print_preformatted "${STATUS}" ${machine_friendly}
+    _print_preformatted "${STATUS}" "${machine_friendly}"
 else
     echo "${STATUS}"
 fi
diff --git a/cqput b/cqput
--- a/cqput
+++ b/cqput
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...] file1 file2 ... 
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...] file1 file2 ... 
 Upload CRX ZIP packages to CRX Package Manager using instance URL.
  
 Examples:
@@ -37,84 +37,83 @@ EOT
 exit 1
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
-if [ $? -ne 0 ]
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
-if [ $? -ne 0 ]
+CURLBIN=$("${API}" -c)
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
 
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":f${apigetopts}" opt; do
-  case $opt in
-     g)  
-      group="$OPTARG";;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+while getopts ":${apigetopts}" opt
+do
+    case ${opt} in
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ $# -eq 0 -o $passed -eq 0 ];
+if [ ${#} -eq 0 -o "${passed}" -eq 0 ];
 then
-	_usage
+    _usage
 fi
 
 
-REFERER="$instance/crx/packmgr"
-AUTH="$username:$password"
+REFERER="${instance}/crx/packmgr"
+AUTH="${username}:${password}"
 FILEPATH="/crx/packmgr/service.jsp"
-REFERERHEADER="Referer: $REFERER"
+REFERERHEADER="Referer: ${REFERER}"
 
 bad=0
-while [ $# -ne 0 ] 
+while [ ${#} -ne 0 ] 
 do
         file=${1}
         if [ ! -f "${file}" ]
         then
-            echo "Cannot find file: ${file}" >&2
+            echo "Cannot find file: '${file}'" >&2
             bad=1
         else
-            STATUS=`$CURLBIN \
-            	-s \
+            STATUS=$(${CURLBIN} \
+                -s \
                 --write-out "%{http_code}" \
-            	-u "$AUTH" \
-            	-H "$REFERERHEADER" \
-                -F file=@"$file" \
+                -u "${AUTH}" \
+                -H "${REFERERHEADER}" \
+                -F file=@"${file}" \
                 -F force=true \
                 -F install=false \
-            	"${instance}${FILEPATH}"`
-            EXITCODE=$?
+                "${instance}${FILEPATH}")
+            EXITCODE=${?}
             "${API}" -C $EXITCODE
-            STATUSCODE=`echo "$STATUS"|tail -n 1`
-            STATUS=`echo "$STATUS"|sed '$d'`
-            "${API}" -H $STATUSCODE
-            EXITCODE2=$?
-            if [ "$EXITCODE" -ne 0 -o "$EXITCODE2" -ne 0 ]
+            STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+            STATUS=$(echo "$STATUS" | sed '$d')
+            "${API}" -H "${STATUSCODE}"
+            EXITCODE2=${?}
+            if [ "${EXITCODE}" -ne 0 -o "${EXITCODE2}" -ne 0 ]
             then
                 bad=1
             else
-                echo "$STATUS"
+                echo "${STATUS}"
                 echo "OK" >&2
             fi
         fi
diff --git a/cqtpm b/cqtpm
--- a/cqtpm
+++ b/cqtpm
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 Invoke TAR PersistenceManager optimization/compaction process for specified CQ
 instance in the background by default with 1 ms sleeping phase between each
 TarPM transaction. There is possibility to invoke compaction in the background
@@ -49,127 +49,130 @@ EOT
 exit 1
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
-if [ $? -ne 0 ]
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
-if [ $? -ne 0 ]
+CURLBIN=$("${API}" -c)
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
 
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 background=true
 pooling=10
 pooling_set=0
 delayms=1
-while getopts ":fs:d:${apigetopts}" opt; do
-  case $opt in
+while getopts ":fs:d:${apigetopts}" opt
+do
+  case ${opt} in
      f)  
       background=false;;
      s)
-      pooling=`echo "$OPTARG"|tr -cd '0-9'|cut -c1-4`; pooling_set=1;;
+      pooling=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-4); pooling_set=1;;
      d)
-      delayms=`echo "$OPTARG"|tr -cd '0-9'|cut -c1-3`;;
+      delayms=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-3);;
     \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
+      echo "Invalid option: -${OPTARG}" >&2; _usage;;
      :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
+      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
   esac
 done
 shift $((OPTIND-1))
 
-if [ $pooling_set -eq 1 -a "$background" = "true" ]
+if [ ${pooling_set} -eq 1 -a "${background}" = "true" ]
 then
     _usage
 fi
 
-if [ $# -ge 1 -o $passed -eq 0 ];
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ];
 then
     _usage
 fi
 
 
-REFERER="$instance/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
-AUTH="$username:$password"
-REFERERHEADER="Referer: $REFERER"
+REFERER="${instance}/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
+AUTH="${username}:${password}"
+REFERERHEADER="Referer: ${REFERER}"
 
-echo -n "Stopping current TarPM compaction (if started)..."
+ECHON=$(which echo)
+[ ${?} -ne 0 -o -z "${ECHON}" ] && ECHON="echo" || ECHON="${ECHON} -n "
+${ECHON} "Stopping current TarPM compaction (if started)..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/stopTar\
 Optimization/"
-STATUS=`$CURLBIN \
-	-s  \
-	-u "$AUTH" \
+STATUS=$(${CURLBIN} \
+    -s  \
+    -u "${AUTH}" \
         --write-out "%{http_code}" \
-	-H "$REFERERHEADER" \
-	-X POST \
-	"$instance${FILEPATH}"`
+    -H "${REFERERHEADER}" \
+    -X POST \
+    "${instance}${FILEPATH}")
 
 
-EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Cannot stop TarPM optimization." >&2
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;s/(null)//'`
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
-"${API}" -H $STATUSCODE
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Cannot stop TarPM optimization." >&2
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
 
 
-echo -n "Setting TarPM compaction sleeping phase..."
+${ECHON} "Setting TarPM compaction sleeping phase..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/a/TarOptimi\
 zationDelay"
-STATUS=`$CURLBIN \
-	-s \
-	-u "$AUTH" \
-        --write-out "%{http_code}" \
-	-H "$REFERERHEADER" \
-        -X POST --data value=$delayms \
-	"$instance${FILEPATH}"`
+STATUS=$(${CURLBIN} \
+    -s \
+    -u "${AUTH}" \
+     --write-out "%{http_code}" \
+    -H "${REFERERHEADER}" \
+    -X POST --data "value=${delayms}" \
+    "${instance}${FILEPATH}")
 
-EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Cannot set compaction delay to ${delay} ms." >&2
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;s/(null)//'`
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
-"${API}" -H $STATUSCODE
+"${API}" -H "${STATUSCODE}"
 EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Cannot set compaction delay to ${delay} ms."
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
 
 
@@ -180,35 +183,35 @@ else
     background_text="background"
 fi
 
-echo -n "Running TarPM compaction in the ${background_text}..."
+${ECHON} "Running TarPM compaction in the ${background_text}..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/startTar\
 Optimization/"
-STATUS=`$CURLBIN \
-	-s \
-	-u "$AUTH" \
-        --write-out "%{http_code}" \
-	-H "$REFERERHEADER" \
-	-X POST  \
-	"$instance${FILEPATH}"`
+STATUS=$(${CURLBIN} \
+    -s \
+    -u "${AUTH}" \
+    --write-out "%{http_code}" \
+    -H "${REFERERHEADER}" \
+    -X POST  \
+    "${instance}${FILEPATH}")
 
-EXITCODE=$?
-"${API}" -C $EXITCODE
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
 
-if [ $EXITCODE -ne 0 ]
+if [ ${EXITCODE} -ne 0 ]
 then
     echo "Cannot start TarPM compaction." >&2
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
-STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;s/(null)//'`
+STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
-"${API}" -H $STATUSCODE
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
     echo "Cannot start TarPM compaction." >&2
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
 
 
@@ -220,24 +223,24 @@ then
     
     while [ "${tarpm_status}" != "0" ]
     do
-        sleep ${pooling}s
-        STATUS=`$CURLBIN \
+        sleep "${pooling}s"
+        STATUS=$(${CURLBIN} \
                     -s \
-                    -u "$AUTH" \
+                    -u "${AUTH}" \
                     --write-out "%{http_code}" \
-                    -H "$REFERERHEADER" \
-                    "${instance}${FILEPATH}"`
-        STATUSCODE=`echo "$STATUS"|tail -n 1`
-        "${API}" -H $STATUSCODE
-        if [ $EXITCODE -ne 0 ]
+                    -H "${REFERERHEADER}" \
+                    "${instance}${FILEPATH}")
+        STATUSCODE=$(echo "${STATUS}" | tail -n 1)
+        "${API}" -H "${STATUSCODE}"
+        if [ ${EXITCODE} -ne 0 ]
         then
             echo "Cannot pool properly TarPM compaction status" >&2
-            exit $EXITCODE
+            exit ${EXITCODE}
         fi
 
 
-        tarpm_status=`echo "$STATUS"|grep TarOptimizationRunningSince\
-                        |tr -cd '0-9 '|tr -s ' '|sed 's#^ *##'|cut -f2 -d ' '`
+        tarpm_status=$(echo "${STATUS}" | grep TarOptimizationRunningSince\
+            | tr -cd '0-9 ' | tr -s ' ' | sed 's#^ *##' | cut -f2 -d ' ')
         if [ -z "${tarpm_status}" ]
         then
             tarpm_status=0
@@ -245,3 +248,4 @@ then
     done
     echo "DONE"
 fi
+
diff --git a/cqwfl b/cqwfl
--- a/cqwfl
+++ b/cqwfl
@@ -15,8 +15,8 @@
 # limitations under the License.
 _usage()
 {
-	cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+    cat << EOT
+Usage: $(basename "${0}") [OPTION...]
 Returns CQ instance active workflows status in pretty-printed form using
 instance URL. Use -j to return original JSON form. Use -m for machine
 
@@ -52,7 +52,7 @@ _generate_regexp_number() {
 _print_preformatted()
 {
     SEP='|'
-    ECHO=`which echo`
+    ECHO=$(which echo)
     if [ ${?} -ne 0 -o -z "${ECHO}" ]
     then
         # fallback to echo
@@ -64,28 +64,28 @@ _print_preformatted()
     machine_friendly=${2}
     full=${3}
 
-    G1=`_generate_regexp "item"`
-    G2=`_generate_regexp "state"`
-    G3=`_generate_regexp "initiator"`
-    G4=`_generate_regexp_number "startTime"`
-    G5=`_generate_regexp "model"`
-    G6=`_generate_regexp "modelVersion"`
-    G7=`_generate_regexp "payload"`
-    G8=`_generate_regexp "comment"`
-    G9=`_generate_regexp "title"`
+    G1=$(_generate_regexp "item")
+    G2=$(_generate_regexp "state")
+    G3=$(_generate_regexp "initiator")
+    G4=$(_generate_regexp_number "startTime")
+    G5=$(_generate_regexp "model")
+    G6=$(_generate_regexp "modelVersion")
+    G7=$(_generate_regexp "payload")
+    G8=$(_generate_regexp "comment")
+    G9=$(_generate_regexp "title")
 
     REGEXP=".*${G1},${G2},${G3},${G4},${G5},${G6},${G7},${G8},${G9}.*"
     [ "${full}" -eq 1 ] && fields_num=9 || fields_num=6
-    items=`echo "${STATUS}" | sed 's#{#\n{#g;' | grep -E \
-        "${REGEXP}" \
+    items=$(echo "${STATUS}" | sed 's#{#\n{#g;' \
+        | grep -E "${REGEXP}" \
         | sed -E "s#${REGEXP}#\4\t\2\t\3\t\5\t\1\t\7\t\6\t\9\t\8#" \
-        | cut -f 1-${fields_num}`
-    total=`$ECHO -e "${items}" | wc -l`
+        | cut -f 1-${fields_num})
+    total=$(${ECHO} -e "${items}" | wc -l)
 
-    if [ $machine_friendly -eq 0 ]
+    if [ "${machine_friendly}" -eq 0 ]
     then
-        $ECHO "${total} workflows."
-        $ECHO ""
+        ${ECHO} "${total} workflows."
+        ${ECHO} ""
         h1="STARTTIME|STATE|INITIATOR|MODEL|ITEM|PAYLOAD"
         h2="|MODEL VERSION|TITLE|COMMENT"
         [ "${full}" -eq 1 ] && output="${h1}${h2}" || output="${h1}"
@@ -93,11 +93,11 @@ _print_preformatted()
     fi
     output="${output}${items}"
 
-    if [ $machine_friendly -eq 1 ]
+    if [ "${machine_friendly}" -eq 1 ]
     then
         ${ECHO} -n "${output}"
     else
-        COLUMN=`which column`
+        COLUMN=$(which column)
         if [ ${?} -ne 0 -o -z "${COLUMN}" ]
         then
             echo "Cannot find column utility"
@@ -108,58 +108,58 @@ _print_preformatted()
     fi
 }
 
-CWD=`dirname "${0}"`
-API="$CWD/cqapi"
-APITEST=`"${API}" -P`
-
-if [ $? -ne 0 ]
+CWD=$(dirname "${0}")
+API="${CWD}/cqapi"
+"${API}" -P >/dev/null
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find or test cqapi command" >&2
-	exit 1
+    echo "Fatal: cannot find or test cqapi command" >&2
+    exit 1
 fi
 
-CURLBIN=`"${API}" -c`
-if [ $? -ne 0 ]
+CURLBIN=$("${API}" -c)
+if [ ${?} -ne 0 ]
 then
-	echo "Fatal: cannot find curl" >&2
-	exit 1
+    echo "Fatal: cannot find curl" >&2
+    exit 1
 fi
 
 
 # API common options
-cmdapi=`    "${API}" -P $@`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 pretty=1
 full=0
 machine_friendly=0
-while getopts ":ljm${apigetopts}" opt; do
-  case $opt in
-     l)
-      full=1;;
-     j)
-      pretty=0;;
-     m)
-      machine_friendly=1;;
-     \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
-     :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
-  esac
+while getopts ":ljm${apigetopts}" opt
+do
+    case ${opt} in
+        l)
+            full=1;;
+        j)
+            pretty=0;;
+        m)
+            machine_friendly=1;;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2; _usage;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    esac
 done
 shift $((OPTIND-1))
 
-if [ $# -gt 0 -o $passed -eq 0 ]
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ]
 then
-	_usage
+    _usage
 fi
 
-if [ $machine_friendly -eq 1 -a $pretty -eq 0 ]
+if [ ${machine_friendly} -eq 1 -a ${pretty} -eq 0 ]
 then
     echo "Switches: -j and -m cannot be applied together."
     _usage
@@ -171,34 +171,35 @@ then
     _usage
 fi
 
-REFERER="$instance/libs/cq/workflow/content/console/instances.html"
-AUTH="$username:$password"
-FILEPATH="/libs/cq/workflow/content/console/instances.json"
-REFERERHEADER="Referer: $REFERER"
+WORKFLOW="/libs/cq/workflow/content/console/instances"
+REFERER="${instance}${WORKFLOW}.html"
+AUTH="${username}:${password}"
+FILEPATH="${WORKFLOW}.json"
+REFERERHEADER="Referer: ${REFERER}"
 
-STATUS=`$CURLBIN \
-	-s \
+STATUS=$(${CURLBIN} \
+    -s \
     --write-out "%{http_code}" \
-	-u "$AUTH" \
-	-H "$REFERERHEADER" \
-	"$instance${FILEPATH}"`
+    -u "${AUTH}" \
+    -H "${REFERERHEADER}" \
+    "${instance}${FILEPATH}")
 
-EXITCODE=$?
-"${API}" -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
-STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-"${API}" -H ${STATUSCODE}
-EXITCODE2=$?
-if [ $EXITCODE2 -ne 0 ]
+STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
+"${API}" -H "${STATUSCODE}"
+EXITCODE2=${?}
+if [ ${EXITCODE2} -ne 0 ]
 then
-    exit $EXITCODE2
+    exit ${EXITCODE2}
 fi
-STATUS=`echo "$STATUS"|sed -r 's#[0-9]{3}$##'`
+STATUS=$(echo "${STATUS}" | sed -r 's#[0-9]{3}$##')
 
-if [ $pretty -eq 1 ]
+if [ ${pretty} -eq 1 ]
 then
     _print_preformatted "$STATUS" ${machine_friendly} ${full}
 else
diff --git a/install b/install
--- a/install
+++ b/install
@@ -20,19 +20,19 @@ then
     exit 1
 fi
 
-ECHO=`which echo`
+ECHO=$(which echo)
 if [ ${?} -ne 0 ]
 then
     ECHO="echo"
 else
     ECHO="${ECHO} -e "
 fi
-dir=`dirname ${0}`
-basedir=`readlink -f ${dir}`
-${ECHO} "I assume that CQ UNIX toolkit are in: ${basedir}\n"
-if [ ! -d "$INSTALL_DIR" ] 
+dir=$(dirname "${0}")
+basedir=$(readlink -f "${dir}")
+${ECHO} "I assume that CQ UNIX toolkit are in: '${basedir}'\n"
+if [ ! -d "${INSTALL_DIR}" ] 
 then
-    echo "Cannot find ${INSTALL_DIR} directory" >&2
+    echo "Cannot find '${INSTALL_DIR}' directory" >&2
     exit 1
 fi
 
@@ -41,23 +41,23 @@ warning=0
 count=0
 total=0
 cmds=""
-for cmd in `ls -1 cq*`
+for cmd in cq*
 do
     total=$((total+1))
-    if [ -f "$INSTALL_DIR/$cmd" ]
+    if [ -f "${INSTALL_DIR}/${cmd}" ]
     then
-        if [ -L "$INSTALL_DIR/$cmd" ]
+        if [ -L "${INSTALL_DIR}/${cmd}" ]
         then
-            target=`readlink -f "$INSTALL_DIR/$cmd"`
-            output="$INSTALL_DIR/$cmd --> ${target} (symbolic link)\n"
+            target=$(readlink -f "${INSTALL_DIR}/${cmd}")
+            output="${INSTALL_DIR}/${cmd} --> ${target} (symbolic link)\n"
         else
-            output="$INSTALL_DIR/$cmd (binary file)\n"
+            output="${INSTALL_DIR}/${cmd} (binary file)\n"
         fi
         count=$((count+1))
         existing_tools="${existing_tools}${output}"
         warning=1
     fi
-    cmds="${cmds} $cmd"
+    cmds="${cmds} ${cmd}"
 done
 if [ ! -z "${existing_tools}" ]
 then
@@ -66,7 +66,8 @@ then
 fi
 
 options=""
-${ECHO} "${total} commands (symbolic links) will be installed in: ${INSTALL_DIR}\n"
+${ECHO} \
+    "${total} commands (symbolic links) will be installed in: ${INSTALL_DIR}\n"
 if [ $warning -eq 1 ]
 then
     ${ECHO} "Would you like to:"
@@ -115,8 +116,9 @@ do
     then
         if [ ${force} -eq 1 -o ! -f "${INSTALL_DIR}/${cmd}" ]
         then
-            ln ${options} -s "${basedir}/$cmd" "${INSTALL_DIR}/${cmd}"
+            ln ${options} -s "${basedir}/${cmd}" "${INSTALL_DIR}/${cmd}"
         fi
     fi
 done
 ${ECHO} "\nInstallation finished."
+
