All scripts re-formatted with Shellcheck

diff --git a/cqbld b/cqbld
--- a/cqbld
+++ b/cqbld
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...] package-name
 Build (rebuild) already uploaded package by group id and name in CQ Package
@@ -36,21 +35,19 @@ Options:
 
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -64,35 +61,36 @@ passed=$(echo "${cmdapi}" | cut -f4)
 apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":g:${apigetopts}" opt
-do
+while getopts ":g:${apigetopts}" opt; do
     case ${opt} in
-        g)
-            group="${OPTARG}";;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    g)
+        group="${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
 name=${1}
 
-if [ -z "${group}" ]
-then
+if [ -z "${group}" ]; then
     group_switch=""
     group_arg=""
 else
     group_switch="-F"
     group_arg="group=${group}"
 fi
-
 
 REFERER="${instance}/crx/packmgr"
 AUTH="${username}:${password}"
@@ -117,4 +115,3 @@ STATUS=$(echo "${STATUS}" | sed '$d')
 EXITCODE2=${?}
 echo "${STATUS}"
 exit $((EXITCODE + EXITCODE2))
-
diff --git a/cqcfg b/cqcfg
--- a/cqcfg
+++ b/cqcfg
@@ -13,9 +13,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
-    cat << EOT
+_usage() {
+    cat <<EOT
 Usage: $(basename "${0}") [OPTION...] [configuration-id]
 Return details of specified OSGI configuration in pretty-printed form or
 machine-friendly form (-m/-n) using instance URL. Allows to modify OSGI
@@ -70,28 +69,25 @@ Options:
   -v VAL                in conjuction with -s, sets value 'VAL' for property
                         specified by -s (multiple times allowed)
 EOT
-exit 1
+    exit 1
 }
 
-
-_print_general_info()
-{
+_print_general_info() {
     DETAILS=$(echo "${STATUS}" | ${SEDX} "s#${PROP_REGEXP}#\1\3#")
     D1='"pid":"([^"]*)"'
     D2='"title":"([^"]*)"'
     D3='"description":"([^"]*)"'
     D4='"bundleLocation":"([^"]*)"'
-    PID=$(echo "${DETAILS}" | grep -E -o "${D1}" \
-        | ${SEDX} "s#.*${D1}.*#\1#")
-    TITLE=$(echo "${DETAILS}" | grep -E -o "${D2}" \
-        | ${SEDX} "s#.*${D2}.*#\1#")
-    DESCRIPTION=$(echo "${DETAILS}" | grep -E -o "${D3}" \
-        | ${SEDX} "s#.*${D3}.*#\1#")
-    BUNDLE=$(echo "${DETAILS}" | grep -E -o "${D4}" \
-        | ${SEDX} "s#.*${D4}.*#\1#")
+    PID=$(echo "${DETAILS}" | grep -E -o "${D1}" |
+        ${SEDX} "s#.*${D1}.*#\1#")
+    TITLE=$(echo "${DETAILS}" | grep -E -o "${D2}" |
+        ${SEDX} "s#.*${D2}.*#\1#")
+    DESCRIPTION=$(echo "${DETAILS}" | grep -E -o "${D3}" |
+        ${SEDX} "s#.*${D3}.*#\1#")
+    BUNDLE=$(echo "${DETAILS}" | grep -E -o "${D4}" |
+        ${SEDX} "s#.*${D4}.*#\1#")
 
-    if [ "${machine_friendly}" -eq 0 ]
-    then
+    if [ "${machine_friendly}" -eq 0 ]; then
         output="PID\t${PID}\n"
         output="${output}TITLE\t${TITLE}\n"
         output="${output}DESCRIPTION\t${DESCRIPTION}\n"
@@ -100,19 +96,17 @@ _print_general_info()
         output="${PID}\n${TITLE}\n${DESCRIPTION}\n${BUNDLE}"
     fi
 
-    if [ "${machine_friendly}" -eq 0 -o "${info}" -eq 1 ]
-    then
+    if [ "${machine_friendly}" -eq 0 -o "${info}" -eq 1 ]; then
         printf "%s\n" "${output}" | "${API}" -F "${machine_friendly}"
     fi
 }
 
-_print_properties()
-{
+_print_properties() {
     T=$(printf '\t')
     PROP_ENTRY_REGEXP='("[^"]+":\{"name":)'
-    PROP_ENTRIES=$(echo "${PROPERTIES}" \
-        | ${SEDX} "s#${PROP_ENTRY_REGEXP}#${T}\1#g" \
-        | tr '\t' '\n')
+    PROP_ENTRIES=$(echo "${PROPERTIES}" |
+        ${SEDX} "s#${PROP_ENTRY_REGEXP}#${T}\1#g" |
+        tr '\t' '\n')
 
     PR12='"([^"]+)":\{"name":"([^"]*)",'
     PR3='"type":(.*),'
@@ -126,40 +120,36 @@ _print_properties()
     VALUES_RG='\{"labels":\[.*\],"values":(\[.*\])\},?'
     SWAPRG="(.*)${T}(.*)${T}(.*)${T}(.*)${T}(.*)}?"
     TYPE_ID_RG="(.*)${T}(.*)${T}(.*)${T}(.*)${T}([0-9]+,?).*"
-    PROPS_BASIC_ROWS=$(echo "${PROP_ENTRIES}" | \
-        grep -E "${PR12}" \
-        | ${SEDX} "s#${PR12}${PR3S}${PR4}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4N}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3A}${PR4A}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4A}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3S}${PR4}#\1${T}\4${T}\2${T}${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4N}#\1${T}\4${T}\2${T}${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3A}${PR4A}#\1${T}\4${T}\2${T}${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4A}#\1${T}\4${T}\2${T}${T}\3#" \
-        | ${SEDX} "s#${PR12}${PR3}${PR4}#\1${T}\4${T}\2${T}${T}\3#" \
-        | ${SEDX} "s#${VALUES_RG}#\1#" \
-        | ${SEDX} "s#${TYPE_ID_RG}#\1${T}\2${T}\3${T}\4${T}#" \
-        | ${SEDX} "s#${SWAPRG}#\1${T}\2${T}\3${T}\5${T}\4#" \
-        | ${SEDX} 's#%22#"#g')
+    PROPS_BASIC_ROWS=$(echo "${PROP_ENTRIES}" |
+        grep -E "${PR12}" |
+        ${SEDX} "s#${PR12}${PR3S}${PR4}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4N}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3A}${PR4A}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4A}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4}${PR5}#\1${T}\4${T}\2${T}\5${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3S}${PR4}#\1${T}\4${T}\2${T}${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4N}#\1${T}\4${T}\2${T}${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3A}${PR4A}#\1${T}\4${T}\2${T}${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4A}#\1${T}\4${T}\2${T}${T}\3#" |
+        ${SEDX} "s#${PR12}${PR3}${PR4}#\1${T}\4${T}\2${T}${T}\3#" |
+        ${SEDX} "s#${VALUES_RG}#\1#" |
+        ${SEDX} "s#${TYPE_ID_RG}#\1${T}\2${T}\3${T}\4${T}#" |
+        ${SEDX} "s#${SWAPRG}#\1${T}\2${T}\3${T}\5${T}\4#" |
+        ${SEDX} 's#%22#"#g')
 
     output="${PROPS_BASIC_ROWS}"
-    if [ "${machine_friendly}" -eq 0 ]
-    then
+    if [ "${machine_friendly}" -eq 0 ]; then
         output="ID\tVALUE\tNAME\tVALUES\tDESCRIPTION\n${output}"
     fi
-    if [ "${long}" -eq 0 ]
-    then
+    if [ "${long}" -eq 0 ]; then
         output=$(printf "%s\n" "${output}" | cut -f1-4)
     fi
-    if [ "${machine_friendly}" -eq 0 -o "${info}" -eq 0 ]
-    then
+    if [ "${machine_friendly}" -eq 0 -o "${info}" -eq 0 ]; then
         printf "%s\n" "${output}" | "${API}" -F "${machine_friendly}"
     fi
 }
 
-_print_configuration()
-{
+_print_configuration() {
     FILEPATH="/system/console/configMgr/${config_id}"
     URL="${instance}${FILEPATH}"
     REFERERHEADER="Referer: ${URL}"
@@ -174,48 +164,42 @@ _print_configuration()
 
     EXITCODE=${?}
     "${API}" -C "${EXITCODE}"
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         exit ${EXITCODE}
     fi
     STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
     "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
+    if [ ${EXITCODE2} -ne 0 ]; then
         exit ${EXITCODE2}
     fi
 
     STATUS=$(echo "${STATUS}" | ${SEDX} 's#[0-9]{3}$##')
 
-    if [ "${original}" -eq 1 ]
-    then
+    if [ "${original}" -eq 1 ]; then
         echo "${STATUS}"
         exit
     fi
 
     PROP_REGEXP='(.*)"properties":\{(.+})}(.*)'
-    PROPERTIES=$(echo "${STATUS}" | ${SEDX} 's#\\\"#%22#g' | \
+    PROPERTIES=$(echo "${STATUS}" | ${SEDX} 's#\\\"#%22#g' |
         grep -E -o "${PROP_REGEXP}" | ${SEDX} "s#${PROP_REGEXP}#\2#")
 
     _print_general_info
-    if [ "${machine_friendly}" -eq 0 ]
-    then
-       printf "\n\n"
+    if [ "${machine_friendly}" -eq 0 ]; then
+        printf "\n\n"
     fi
     _print_properties
     exit
 }
 
-_modify_configuration()
-{
+_modify_configuration() {
     CONFIGMGR="/system/console/configMgr/"
     original_config_id=$(echo "${config_id}" | sed 's#%20# #g')
 
-    if [ "${factory}" -eq 1 ]
-    then
+    if [ "${factory}" -eq 1 ]; then
         echo "Using factory: '${original_config_id}'."
-        temp_pid=$(echo "[Temporary PID replaced by real PID upon save]" | \
+        temp_pid=$(echo "[Temporary PID replaced by real PID upon save]" |
             "${API}" -f)
         FACTORY="factoryPid=${config_id}&"
         FILEPATH="${CONFIGMGR}${temp_pid}"
@@ -229,26 +213,24 @@ _modify_configuration()
     REFERERHEADER="Referer: ${instance}${FILEPATH}"
     first=1
     UNIQUE_PROPERTIES=""
-    for operation in ${operations}
-    do
+    for operation in ${operations}; do
         propname=$(echo "${operation}" | cut -f1 -d '=')
         propvalue=$(echo "${operation}" | cut -f2- -d '=' | "${API}" -f)
 
-        prop_original_value=$(echo "${operation}" | cut -f2- -d '=' |\
+        prop_original_value=$(echo "${operation}" | cut -f2- -d '=' |
             sed 's#%20# #g')
         echo "  Setting '${propname}' to: '${prop_original_value}' "
 
         [ "${first}" -eq 0 ] && REQ_ACTION="${REQ_ACTION}&"
         REQ_ACTION="${REQ_ACTION}${propname}=${propvalue}"
-        UNIQUE_PROPERTIES=$(printf "%s\n%s\n" "${UNIQUE_PROPERTIES}"\
+        UNIQUE_PROPERTIES=$(printf "%s\n%s\n" "${UNIQUE_PROPERTIES}" \
             "${propname}")
         first=0
     done
-    UNIQUE_PROPERTIES=$(printf "%s\n" "${UNIQUE_PROPERTIES}" | sort | \
-        uniq )
+    UNIQUE_PROPERTIES=$(printf "%s\n" "${UNIQUE_PROPERTIES}" | sort |
+        uniq)
     first=1
-    for property in ${UNIQUE_PROPERTIES}
-    do
+    for property in ${UNIQUE_PROPERTIES}; do
         [ "${first}" -eq 0 ] && PROPERTIES="${PROPERTIES}%2C"
         PROPERTIES="${PROPERTIES}${property}"
         first=0
@@ -265,26 +247,22 @@ _modify_configuration()
 
     EXITCODE=${?}
     "${API}" -C $EXITCODE
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         exit ${EXITCODE}
     fi
     STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | head -n 1)
-    NEW_CONFIG_ID=$(echo "${STATUS}" | tail -n 1 | \
+    NEW_CONFIG_ID=$(echo "${STATUS}" | tail -n 1 |
         ${SEDX} "s#.*(${config_id}.*)#\1#")
 
     TEMPORARY_REDIRECT="302"
-    if [ ! "${STATUSCODE}" = "${TEMPORARY_REDIRECT}" ]
-    then
+    if [ ! "${STATUSCODE}" = "${TEMPORARY_REDIRECT}" ]; then
         "${API}" -H "${STATUSCODE}"
         EXITCODE2=$?
-        if [ ${EXITCODE2} -ne 0 ]
-        then
+        if [ ${EXITCODE2} -ne 0 ]; then
             exit ${EXITCODE2}
         fi
     fi
-    if [ "${factory}" -eq 1 ]
-    then
+    if [ "${factory}" -eq 1 ]; then
         echo "New configuration created: ${NEW_CONFIG_ID}"
     fi
     exit
@@ -294,15 +272,13 @@ CWD=$(dirname "${0}")
 API="$CWD/cqapi"
 "${API}" -P >/dev/null 2>/dev/null
 
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -329,65 +305,71 @@ factory=0
 v_counter=0
 s_counter=0
 while getopts ":lfjmns:v:${apigetopts}" opt; do
-  case "${opt}" in
-     j)
-      original=1;;
-     m)
-      machine_friendly=1;;
-     n)
-      info=1;;
-     l)
-      long=1;;
-     f)
-      factory=1;;
-     v)
-      v_counter=$((v_counter+1))
-      modify=1
-      if [ ! -z "${property_id}" ]
-      then
-          propvalue=$(echo "${OPTARG}" | sed 's# #%20#g')
-          operations="${operations} ${property_id}=${propvalue}"
-          property_id=""
-      else
-          echo "For each -v option there must be -s preceeding"\
-            "option specified" >&2
-          echo "" >&2
-          _usage
-      fi;;
-     s)
-      s_counter=$((s_counter+1))
-      modify=1;
-      property_id="${OPTARG}";;
-     \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+    case "${opt}" in
+    j)
+        original=1
+        ;;
+    m)
+        machine_friendly=1
+        ;;
+    n)
+        info=1
+        ;;
+    l)
+        long=1
+        ;;
+    f)
+        factory=1
+        ;;
+    v)
+        v_counter=$((v_counter + 1))
+        modify=1
+        if [ ! -z "${property_id}" ]; then
+            propvalue=$(echo "${OPTARG}" | sed 's# #%20#g')
+            operations="${operations} ${property_id}=${propvalue}"
+            property_id=""
+        else
+            echo "For each -v option there must be -s preceeding" \
+                "option specified" >&2
+            echo "" >&2
+            _usage
+        fi
+        ;;
+    s)
+        s_counter=$((s_counter + 1))
+        modify=1
+        property_id="${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
-if [ "${s_counter}" -ne "${v_counter}" ]
-then
+if [ "${s_counter}" -ne "${v_counter}" ]; then
     echo "Options: -s and -v are connected together. You need to specify" \
-     "matching pairs of such options (property/value)." >&2
+        "matching pairs of such options (property/value)." >&2
     echo ""
     _usage
 fi
 
 config_id="${1}"
-if [ "${machine_friendly}" -eq 1 -a "${original}" -eq 1 ]
-then
+if [ "${machine_friendly}" -eq 1 -a "${original}" -eq 1 ]; then
     echo "Switches: -j and -m cannot be applied together." >&2
     echo ""
     _usage
 fi
-if [ "${machine_friendly}" -eq 0 -a "${info}" -eq 1 ]
-then
+if [ "${machine_friendly}" -eq 0 -a "${info}" -eq 1 ]; then
     echo "Option: -n is dedicated for -m (machine-friendly output)." >&2
     echo ""
     _usage
@@ -395,9 +377,8 @@ fi
 
 AUTH="${username}:${password}"
 config_id=$(echo "${config_id}" | sed 's# #%20#g')
-view_options=$((original+info+machine_friendly))
-if [ -z "${operations}" -a "${factory}" -eq 1 ]
-then
+view_options=$((original + info + machine_friendly))
+if [ -z "${operations}" -a "${factory}" -eq 1 ]; then
     echo "New configuration from factory -f option must be applied" \
         "together with modify operations: -s/-v" >&2
     echo "See what properties are supported. Call this command with factory" \
@@ -407,14 +388,11 @@ then
     exit 2
 fi
 
-if [ "${operations}" != "" -a "${view_options}" -ge 1 ]
-then
+if [ "${operations}" != "" -a "${view_options}" -ge 1 ]; then
     echo "View options -m, -j, -n or -l cannot be applied together " \
         "with modify operations: -s/-v. Choose only one functionality." >&2
     exit 2
 fi
 
-
 [ "${modify}" -eq 0 ] && _print_configuration
 [ "${modify}" -eq 1 ] && _modify_configuration
-
diff --git a/cqcfgdel b/cqcfgdel
--- a/cqcfgdel
+++ b/cqcfgdel
@@ -13,9 +13,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
-    cat << EOT
+_usage() {
+    cat <<EOT
 Usage: $(basename "${0}") [OPTION...] configuration-id
 Delete specified OSGI configuration from instance passed as -i URL option.
 Please be cautious before deletion unknown configuration. This may harm your
@@ -38,11 +37,10 @@ Options:
   -i                    use specified instance URL to connect
 
 EOT
-exit 1
+    exit 1
 }
 
-_delete_configuration()
-{
+_delete_configuration() {
     CONFIGMGR="/system/console/configMgr/"
     original_config_id=$(echo "${config_id}" | sed 's#%20# #g')
 
@@ -64,37 +62,31 @@ _delete_configuration()
 
     EXITCODE=${?}
     "${API}" -C $EXITCODE
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         exit ${EXITCODE}
     fi
     STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | head -n 1)
     "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
+    if [ ${EXITCODE2} -ne 0 ]; then
         exit ${EXITCODE2}
     fi
     exit
 }
 
-
 CWD=$(dirname "${0}")
 API="$CWD/cqapi"
 "${API}" -P >/dev/null 2>/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
-
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
@@ -106,17 +98,20 @@ apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
 while getopts ":${apigetopts}" opt; do
-  case "${opt}" in
-     \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+    case "${opt}" in
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
@@ -125,4 +120,3 @@ config_id=$(echo "${config_id}" | sed 's# #%20#g')
 AUTH="${username}:${password}"
 
 _delete_configuration
-
diff --git a/cqcfgls b/cqcfgls
--- a/cqcfgls
+++ b/cqcfgls
@@ -13,9 +13,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
-    cat << EOT
+_usage() {
+    cat <<EOT
 Usage: $(basename "${0}") [OPTION...]
 Return CQ instance list of OSGI configurations using instance URL.
 
@@ -32,11 +31,10 @@ Options:
   -i                    use specified instance URL to connect
 
 EOT
-exit 1
+    exit 1
 }
 
-_list_configurations()
-{
+_list_configurations() {
     FILEPATH="/system/console/components.json"
     URL="${instance}${FILEPATH}"
     REFERERHEADER="Referer: ${URL}"
@@ -50,21 +48,19 @@ _list_configurations()
 
     EXITCODE=${?}
     "${API}" -C "${EXITCODE}"
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         exit ${EXITCODE}
     fi
     STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
     "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
+    if [ ${EXITCODE2} -ne 0 ]; then
         exit ${EXITCODE2}
     fi
     CONFIG_REGEXP='"configurable":"([^"]+)"'
     STATUS=$(echo "${STATUS}" | ${SEDX} 's#[0-9]{3}$##')
 
-    CLEARED_STATUS=$(echo "${STATUS}" | ${SEDX} 's#\{#\n{#g' | \
+    CLEARED_STATUS=$(echo "${STATUS}" | ${SEDX} 's#\{#\n{#g' |
         grep -E -o "${CONFIG_REGEXP}" | ${SEDX} "s#${CONFIG_REGEXP}#\1#")
 
     FILEPATH="/system/console/config/Configurations.nfo"
@@ -80,41 +76,36 @@ _list_configurations()
 
     EXITCODE=${?}
     "${API}" -C ${EXITCODE}
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         exit ${EXITCODE}
     fi
     STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
     "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
+    if [ ${EXITCODE2} -ne 0 ]; then
         exit ${EXITCODE2}
     fi
 
     STATUS=$(echo "${STATUS}" | sed '$d')
-    CLEARED_STATUS2=$(echo "${STATUS}" | grep '^PID' | ${SEDX} 's#&nbsp;# #g' \
-        | ${SEDX} 's#<br/>##g' | cut -f2- -d '=' \
-        | ${SEDX} 's#^[ ]+##; s#[ ]+$##')
+    CLEARED_STATUS2=$(echo "${STATUS}" | grep '^PID' | ${SEDX} 's#&nbsp;# #g' |
+        ${SEDX} 's#<br/>##g' | cut -f2- -d '=' |
+        ${SEDX} 's#^[ ]+##; s#[ ]+$##')
 
     printf "%s\n%s" "${CLEARED_STATUS}" "${CLEARED_STATUS2}" | sort | uniq
     exit 0
 }
 
-
 CWD=$(dirname "${0}")
 API="$CWD/cqapi"
 "${API}" -P >/dev/null 2>/dev/null
 
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -130,21 +121,23 @@ passed=$(echo "${cmdapi}" | cut -f4)
 apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 while getopts ":${apigetopts}" opt; do
-  case "${opt}" in
-     \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+    case "${opt}" in
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -gt 0 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
 AUTH="${username}:${password}"
 
 _list_configurations
-
diff --git a/cqchk b/cqchk
--- a/cqchk
+++ b/cqchk
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...]
 Invoke CRX repository check and fix on them. By default fixes are not performed.
@@ -35,21 +34,19 @@ Options:
   -f                    force fixing erros when possible
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -66,18 +63,22 @@ apigetopts=$(echo "${cmdapi}" | cut -f5)
 fix=false
 while getopts ":f${apigetopts}" opt; do
     case "${opt}" in
-        f)
-            fix=true;;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    f)
+        fix=true
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ge 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
@@ -90,7 +91,6 @@ FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/traversa\
 lCheck/java.lang.String%2Cjava.lang.Boolean%2Cjava.lang.Boolean"
 REFERERHEADER="Referer: ${REFERER}"
 
-
 STATUS=$(${CURLBIN} \
     -s \
     --write-out "%{http_code}" \
@@ -101,8 +101,7 @@ STATUS=$(${CURLBIN} \
 
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot invoke repository traversal check." >&2
     exit ${EXITCODE}
 fi
@@ -112,12 +111,10 @@ STATUS=$(echo "${STATUS}" | sed '$d;')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot invoke repository traversal check." >&2
     exit ${EXITCODE2}
 fi
-
 
 ${ECHON} "Starting repository consistency check..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/consiste\
@@ -131,8 +128,7 @@ STATUS=$(${CURLBIN} \
     "${instance}${FILEPATH}")
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot invoke repository consistency check." >&2
     exit ${EXITCODE}
 fi
@@ -142,9 +138,7 @@ STATUS=$(echo "${STATUS}" | sed '$d;')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot invoke repository consistency check." >&2
     exit ${EXITCODE2}
 fi
-
diff --git a/cqclr b/cqclr
--- a/cqclr
+++ b/cqclr
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...]
 Clear cache for specified dispatcher (-i option). By default clear the whole
@@ -47,25 +46,22 @@ Options:
                         (by default the whole cache so: '/' node)
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
-
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
@@ -77,26 +73,29 @@ apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 path="/"
 vhost=""
-while getopts ":r:v:${apigetopts}" opt
-do
+while getopts ":r:v:${apigetopts}" opt; do
     case ${opt} in
-        r)
-            path="${OPTARG}";;
-        v)
-            vhost="${OPTARG}";;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    r)
+        path="${OPTARG}"
+        ;;
+    v)
+        vhost="${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ge 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
-
 
 URL="${instance}/dispatcher/invalidate.cache"
 REFERER=${URL}
@@ -106,8 +105,7 @@ VHOSTHEADER=""
 echo "Clearing dispatcher cache:"
 echo "                     path: ${path}"
 
-if [ "${vhost}" != "" ]
-then
+if [ "${vhost}" != "" ]; then
     VHOSTHEADER="Host: ${vhost}"
     echo "           requested host: ${vhost}"
 fi
@@ -116,25 +114,23 @@ echo "           connection URL: ${instance}"
 echo ""
 
 STATUS=$(${CURLBIN} -s -X POST \
-        --output /dev/null \
-        --write-out %{http_code} \
-        -u "${AUTH}" \
-        -H "CQ-Action: Delete" \
-        -H "CQ-Handle: ${path}" \
-        -H "Content-Length: 0" \
-        -H "${VHOSTHEADER}" \
-        -H "${REFERERHEADER}" \
-        "${URL}")
+    --output /dev/null \
+    --write-out %{http_code} \
+    -u "${AUTH}" \
+    -H "CQ-Action: Delete" \
+    -H "CQ-Handle: ${path}" \
+    -H "Content-Length: 0" \
+    -H "${VHOSTHEADER}" \
+    -H "${REFERERHEADER}" \
+    "${URL}")
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     exit ${EXITCODE}
 fi
 "${API}" -H "${STATUS}"
 EXITCODE=${?}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     exit ${EXITCODE}
 fi
 
diff --git a/cqcp b/cqcp
--- a/cqcp
+++ b/cqcp
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...] package-resource-name
 Makes local copy of already uploaded package by group id and name in CQ Package
@@ -38,21 +37,19 @@ Options:
                         or path
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -66,23 +63,27 @@ passed=$(echo "${cmdapi}" | cut -f4)
 apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":o:g:${apigetopts}" opt
-do
+while getopts ":o:g:${apigetopts}" opt; do
     case ${opt} in
-        g)
-            group="${OPTARG}";;
-        o)
-            outfile="${OPTARG}";;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    g)
+        group="${OPTARG}"
+        ;;
+    o)
+        outfile="${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 -o "${passed}" -eq 0 ];
-then
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 name=${1}
@@ -90,8 +91,7 @@ name=${1}
 group_switch="-F"
 group_arg="group=${group}"
 
-if [ -z "${outfile}" ]
-then
+if [ -z "${outfile}" ]; then
     outfile="${name}.zip"
 fi
 redirection="${outfile}"
@@ -121,19 +121,16 @@ CONTENTTYPE=$(echo "${STATUSFIELDS}" | cut -f1 -d ' ')
 EXITCODE2=${?}
 fullfile=$(readlink -f "${outfile}")
 plain=0
-if [ "${EXITCODE2}" -eq 0 -a ${EXITCODE} -eq 0 ]
-then
+if [ "${EXITCODE2}" -eq 0 -a ${EXITCODE} -eq 0 ]; then
     plain=$(echo "${CONTENTTYPE}" | grep -c 'plain')
 fi
 
 EXITCODE=$((EXITCODE + EXITCODE2))
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     exit ${EXITCODE}
 fi
 
-if [ "${plain}" -eq 1 ]
-then
+if [ "${plain}" -eq 1 ]; then
     redirection="-"
 fi
 
@@ -154,14 +151,11 @@ STATUSCODE=$(echo "${STATUS}" | tail -n 1 | cut -f2- -d ' ')
 STATUS=$(echo "${STATUS}" | sed '$d')
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -eq 0 -a ${EXITCODE} -eq 0 ]
-then
-    if [ "${plain}" -eq 0 ]
-    then
+if [ ${EXITCODE2} -eq 0 -a ${EXITCODE} -eq 0 ]; then
+    if [ "${plain}" -eq 0 ]; then
         echo "Package copied to: '${fullfile}'"
     else
         echo "${STATUS}"
     fi
 fi
 exit $((EXITCODE + EXITCODE2))
-
diff --git a/cqgc b/cqgc
--- a/cqgc
+++ b/cqgc
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...]
 Invoke DataStore compaction/garbage collection operation for specified CQ
@@ -40,21 +39,19 @@ Options:
   -f                    stops current GC session
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -70,26 +67,29 @@ apigetopts=$(echo "${cmdapi}" | cut -f5)
 # Custom arguments
 delay_ms=15
 force_stop=0
-while getopts ":d:f${apigetopts}" opt
-do
+while getopts ":d:f${apigetopts}" opt; do
     case ${opt} in
-        d)
-            delay_ms=$(echo "${OPTARG}" | tr -cd '[:digit:]');;
-        f)
-            force_stop=1;;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    d)
+        delay_ms=$(echo "${OPTARG}" | tr -cd '[:digit:]')
+        ;;
+    f)
+        force_stop=1
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -gt 0 -o "${passed}" -eq 0 ];
-then
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ]; then
     _usage
 fi
-
 
 REFERER="${instance}/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
 AUTH="${username}:${password}"
@@ -104,22 +104,20 @@ REFERERHEADER="Referer: ${REFERER}"
 ECHON=$(which echo)
 [ ${?} -ne 0 -o -z "${ECHON}" ] && ECHON="echo" || ECHON="${ECHON} -n "
 # Stopping GC sleeping phase delay
-if [ ${force_stop} -eq 1 ]
-then
+if [ ${force_stop} -eq 1 ]; then
     ${ECHON} "Stopping DataStore garbage collection (if working)..."
     STATUS=$(${CURLBIN} \
-           -s \
-           --write-out "%{http_code}" \
-           -u "${AUTH}" \
-           -H "${REFERERHEADER}" \
-           -X POST \
-           "${instance}${FILEPATH3}")
+        -s \
+        --write-out "%{http_code}" \
+        -u "${AUTH}" \
+        -H "${REFERERHEADER}" \
+        -X POST \
+        "${instance}${FILEPATH3}")
 
     EXITCODE=${?}
     "${API}" -C ${EXITCODE}
 
-    if [ ${EXITCODE} -ne 0 ]
-    then
+    if [ ${EXITCODE} -ne 0 ]; then
         echo "Cannot stop current garbage collection." >&2
         exit ${EXITCODE}
     fi
@@ -130,14 +128,12 @@ then
     "${API}" -H "${STATUSCODE}"
 
     EXITCODE2=${?}
-    if [ ${EXITCODE2} -ne 0 ]
-    then
+    if [ ${EXITCODE2} -ne 0 ]; then
         echo "Cannot stop current garbage collection." >&2
         exit ${EXITCODE2}
     fi
     sleep 5s
 fi
-
 
 # Setting GC sleeping phase delay
 ${ECHON} "Setting DataStore garbage collection sleeping phase..."
@@ -152,8 +148,7 @@ STATUS=$(${CURLBIN} \
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
 
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot set garbage collection sleeping phase." >&2
     exit ${EXITCODE}
 fi
@@ -163,8 +158,7 @@ STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//;s/^$/DONE/;')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot set garbage collection sleeping phase." >&2
     exit ${EXITCODE2}
 fi
@@ -182,8 +176,7 @@ STATUS=$(${CURLBIN} \
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
 
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot invoke garbage collection." >&2
     exit ${EXITCODE}
 fi
@@ -191,17 +184,14 @@ fi
 STATUSCODE=$(echo "${STATUS}" | tail -n 1)
 STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//;s/^$/DONE/')
 is_exception=$(echo "${STATUS}" | "${API}" -e)
-if [ "${is_exception}" -ge 0 ]
-then
+if [ "${is_exception}" -ge 0 ]; then
     STATUS=$(echo "${STATUS}" | "${API}" -E)
 fi
 echo "${STATUS}"
 
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot invoke garbage collection." >&2
     exit ${EXITCODE2}
 fi
-
diff --git a/cqget b/cqget
--- a/cqget
+++ b/cqget
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...] URL
 Download specified file or resource using full URL specification. Normally
@@ -36,21 +35,19 @@ Options:
 
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
@@ -62,21 +59,24 @@ password=$(echo "${cmdapi}" | cut -f2)
 apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":o:${apigetopts}" opt
-do
+while getopts ":o:${apigetopts}" opt; do
     case "${opt}" in
-        o)
-            outfile="${OPTARG}";;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    o)
+        outfile="${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 ];
-then
+if [ ${#} -ne 1 ]; then
     _usage
 fi
 URL=${1}
@@ -84,11 +84,9 @@ REFERER="${URL}"
 AUTH="${username}:${password}"
 REFERERHEADER="Referer: ${REFERER}"
 
-if [ -z "${outfile}" ]
-then
+if [ -z "${outfile}" ]; then
     outfile=$(basename "${URL}")
 fi
-
 
 STATUS=$(${CURLBIN} \
     -s \
@@ -106,14 +104,11 @@ STATUSCODE=$(echo "${STATUS}" | tail -n 1)
 "${API}" -H "${STATUSCODE}"
 
 EXITCODE2=${?}
-if [ ${EXITCODE} -eq 0 -a ${EXITCODE} -eq 0 ]
-then
-    if [ ! -z "${outfile}" ]
-    then
+if [ ${EXITCODE} -eq 0 -a ${EXITCODE} -eq 0 ]; then
+    if [ ! -z "${outfile}" ]; then
         fullfile=$(readlink -f "${outfile}")
         echo "Resource copied to: '${fullfile}'"
     fi
 fi
 
 exit $((EXITCODE + EXITCODE2))
-
diff --git a/cqpkg b/cqpkg
--- a/cqpkg
+++ b/cqpkg
@@ -13,9 +13,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
-	cat <<EOT
+_usage() {
+    cat <<EOT
 Usage: $(basename "${0}") [SPECIFICATION...] package-name
 Create minimal empty CQ Vault ZIP package locally using provided specification
 that can be uploaded to CRX/CQ Package Manager and built or installed.
@@ -60,53 +59,53 @@ Options:
 
 
 EOT
-exit 1
+    exit 1
 }
 
-_add_filter()
-{
-    filter_definition=$(cat <<EOF
+_add_filter() {
+    filter_definition=$(
+        cat <<EOF
 ${filter_definition}
 <filter root="${1}">
 EOF
     )
 }
 
-_add_include_entry()
-{
-    filter_definition=$(cat <<EOF
+_add_include_entry() {
+    filter_definition=$(
+        cat <<EOF
 ${filter_definition}
   <include pattern="${1}"/>
 EOF
     )
 }
 
-_add_exclude_entry()
-{
-    filter_definition=$(cat <<EOF
+_add_exclude_entry() {
+    filter_definition=$(
+        cat <<EOF
 ${filter_definition}
   <exclude pattern="${1}"/>
 EOF
     )
 }
 
-
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
-filter_definition=$(cat <<EOT
+filter_definition=$(
+    cat <<EOT
 <?xml version="1.0" encoding="UTF-8"?>
 <workspaceFilter version="1.0">
 EOT
 )
 toolkit_version=$("${API}" -v)
-package_definition=$(cat <<EOT
+package_definition=$(
+    cat <<EOT
 <?xml version="1.0" encoding="utf-8" standalone="no"?>
 <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
 <properties>
@@ -122,75 +121,85 @@ description="Package genereated by CQ Unix Toolkit ${toolkit_version}"
 in_filter_context=0
 version="1.0"
 
-while getopts ":g:v:r:i:e:o:d:" opt
-do
+while getopts ":g:v:r:i:e:o:d:" opt; do
     case "${opt}" in
-        g)
-            group="${OPTARG}";;
-        v)
-            version="${OPTARG}";;
-        d)
-            description="${OPTARG}";;
-        o)
-            zipfilename="${OPTARG}";;
-        r)
-            if [ ${in_filter_context} -eq 1 ]
-            then
-                filter_definition="${filter_definition}\n</filter>"
-            fi
-            in_filter_context=1
-            _add_filter "${OPTARG}";;
-        i)
-            if [ ${in_filter_context} -eq 0 ]
-            then
-                echo "Include pattern (-i) should be nested in scope of" \
-                    "filter root path (-r)." >&2
-                echo "Please add -r JCRPATH before adding -i/-e options." >&2
-                exit 1;
-            fi
-            _add_include_entry "${OPTARG}";;
-        e)
-            if [ ${in_filter_context} -eq 0 ]
-            then
-                echo "Exclude pattern (-e) should be nested in scope of" \
-                    "filter root path (-r)." >&2
-                echo "Please add -r JCRPATH before adding -i/-e options." >&2
-                exit 1;
-            fi
-            _add_exclude_entry "${OPTARG}";;
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    g)
+        group="${OPTARG}"
+        ;;
+    v)
+        version="${OPTARG}"
+        ;;
+    d)
+        description="${OPTARG}"
+        ;;
+    o)
+        zipfilename="${OPTARG}"
+        ;;
+    r)
+        if [ ${in_filter_context} -eq 1 ]; then
+            filter_definition="${filter_definition}\n</filter>"
+        fi
+        in_filter_context=1
+        _add_filter "${OPTARG}"
+        ;;
+    i)
+        if [ ${in_filter_context} -eq 0 ]; then
+            echo "Include pattern (-i) should be nested in scope of" \
+                "filter root path (-r)." >&2
+            echo "Please add -r JCRPATH before adding -i/-e options." >&2
+            exit 1
+        fi
+        _add_include_entry "${OPTARG}"
+        ;;
+    e)
+        if [ ${in_filter_context} -eq 0 ]; then
+            echo "Exclude pattern (-e) should be nested in scope of" \
+                "filter root path (-r)." >&2
+            echo "Please add -r JCRPATH before adding -i/-e options." >&2
+            exit 1
+        fi
+        _add_exclude_entry "${OPTARG}"
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 ]
-then
+if [ ${#} -ne 1 ]; then
     _usage
 fi
-group_entry=$(cat <<EOT
+group_entry=$(
+    cat <<EOT
 <entry key="group">${group}</entry>
 EOT
 )
 name=${1}
 dir=$(pwd)
-if [ -z "${zipfilename}" ]
-then
+if [ -z "${zipfilename}" ]; then
     zipfile="${dir}/${name}-${version}.zip"
 else
-    zipfile=$(cd $(dirname "${zipfilename}"); \
-        pwd)/$(basename "${zipfilename}")
+    zipfile=$(
+        cd $(dirname "${zipfilename}")
+        pwd
+    )/$(basename "${zipfilename}")
 fi
 
-filter_definition=$(cat <<EOT
+filter_definition=$(
+    cat <<EOT
 ${filter_definition}
 </filter>
 </workspaceFilter>
 EOT
 )
-package_definition=$(cat <<EOT
+package_definition=$(
+    cat <<EOT
 ${package_definition}
 ${group_entry}
 <entry key="name">${name}</entry>
@@ -200,15 +209,13 @@ ${group_entry}
 EOT
 )
 ZIP=$(which zip)
-if [ ${?} -ne 0 -o "${ZIP}" = "" ]
-then
+if [ ${?} -ne 0 -o "${ZIP}" = "" ]; then
     echo "Cannot find zip packaging command-line tool. Aborted" >&2
     exit 2
 fi
 tempdir=$(mktemp -d cqpkgXXXXXXXXXX)
 exitcode=${?}
-if [ ${exitcode} -ne 0 ]
-then
+if [ ${exitcode} -ne 0 ]; then
     echo "Cannot create temporary directory ${tempdir}. Aborted" >&2
     exit 1
 fi
@@ -216,14 +223,13 @@ vault="${tempdir}/META-INF/vault"
 mkdir -p "${tempdir}/jcr_root"
 mkdir -p "${vault}"
 
-printf "%s" "${filter_definition}" > "${vault}/filter.xml"
-printf "%s" "${package_definition}" > "${vault}/properties.xml"
+printf "%s" "${filter_definition}" >"${vault}/filter.xml"
+printf "%s" "${package_definition}" >"${vault}/properties.xml"
 cd "${tempdir}"
-"${ZIP}" -q -r - ./ > "${zipfile}"
+"${ZIP}" -q -r - ./ >"${zipfile}"
 exitcode=${?}
 cd "${dir}"
-if [ ${exitcode} -ne 0 ]
-then
+if [ ${exitcode} -ne 0 ]; then
     echo "Cannot create zip package properly." >&2
 fi
 rm "${vault}/filter.xml"
@@ -233,8 +239,7 @@ rmdir "${tempdir}/META-INF/vault"
 rmdir "${tempdir}/META-INF"
 rmdir "${tempdir}"
 
-if [ ${exitcode} -eq 0 ]
-then
+if [ ${exitcode} -eq 0 ]; then
     echo "Empty package created: '${zipfile}'"
 else
     exit 3
diff --git a/cqput b/cqput
--- a/cqput
+++ b/cqput
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...] file1 file2 ... 
 Upload CRX ZIP packages to CRX Package Manager using instance URL.
@@ -34,25 +33,22 @@ Options:
 
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
-
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
@@ -63,22 +59,23 @@ passed=$(echo "${cmdapi}" | cut -f4)
 apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 # Custom arguments
-while getopts ":${apigetopts}" opt
-do
+while getopts ":${apigetopts}" opt; do
     case ${opt} in
-        \?)
-            echo "Invalid option: -${OPTARG}" >&2; _usage;;
-        :)
-            echo "Option -${OPTARG} requires an argument." >&2; _usage;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
     esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -eq 0 -o "${passed}" -eq 0 ];
-then
+if [ ${#} -eq 0 -o "${passed}" -eq 0 ]; then
     _usage
 fi
-
 
 REFERER="${instance}/crx/packmgr"
 AUTH="${username}:${password}"
@@ -86,11 +83,9 @@ FILEPATH="/crx/packmgr/service.jsp"
 REFERERHEADER="Referer: ${REFERER}"
 
 bad=0
-while [ ${#} -ne 0 ] 
-do
+while [ ${#} -ne 0 ]; do
     file=${1}
-    if [ ! -f "${file}" ]
-    then
+    if [ ! -f "${file}" ]; then
         echo "Cannot find file: '${file}'" >&2
         bad=1
     else
@@ -109,8 +104,7 @@ do
         STATUS=$(echo "${STATUS}" | sed '$d')
         "${API}" -H "${STATUSCODE}"
         EXITCODE2=${?}
-        if [ "${EXITCODE}" -ne 0 -o "${EXITCODE2}" -ne 0 ]
-        then
+        if [ "${EXITCODE}" -ne 0 -o "${EXITCODE2}" -ne 0 ]; then
             bad=1
         else
             echo "${STATUS}"
@@ -119,7 +113,6 @@ do
     fi
     shift
 done
-if [ ${bad} -eq 1 ]
-then
+if [ ${bad} -eq 1 ]; then
     exit 1
 fi
diff --git a/cqsnp b/cqsnp
--- a/cqsnp
+++ b/cqsnp
@@ -13,9 +13,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
-	cat << EOT
+_usage() {
+    cat <<EOT
 Usage: $(basename "${0}") [OPTION...] package-name
 Download installation snapshot specified by package name and optionally group
 and version. Optionally package can be dropped from CQ after downloading.
@@ -60,25 +59,22 @@ Options:
   -0                    only in conjunction with -d package is not saved at all
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
-"${API}" -P 2> /dev/null > /dev/null
-if [ ${?} -ne 0 ]
-then
+"${API}" -P 2>/dev/null >/dev/null
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
-
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
@@ -94,40 +90,45 @@ null=0
 file=0
 version="1.0"
 while getopts ":o:dv:g:0${apigetopts}" opt; do
-  case "${opt}" in
-     o)
-      outfile="${OPTARG}";
-      file=1;;
-     g)
-      group_name="${OPTARG}";;
-     v)
-      version="${OPTARG}";;
-     d)
-      drop=1;;
-     0)
-      null=1;;
-     \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+    case "${opt}" in
+    o)
+        outfile="${OPTARG}"
+        file=1
+        ;;
+    g)
+        group_name="${OPTARG}"
+        ;;
+    v)
+        version="${OPTARG}"
+        ;;
+    d)
+        drop=1
+        ;;
+    0)
+        null=1
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${#} -ne 1 -o "${passed}" -eq 0 ]
-then
+if [ ${#} -ne 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
 
-if [ ${drop} -eq 0 -a ${null} -eq 1 ]
-then
+if [ ${drop} -eq 0 -a ${null} -eq 1 ]; then
     echo "Option -0 requires to pass -d explicitly." >&2
     _usage
 fi
 
-
-if [ ${null} -eq 1 -a ${file} -eq 1 ]
-then
+if [ ${null} -eq 1 -a ${file} -eq 1 ]; then
     echo "Option -o cannot be used together with -0." >&2
     echo "What is your intention?" >&2
     echo " 1) save snapshot before dropping it from CQ (-o)" >&2
@@ -147,93 +148,81 @@ CQ_PKG_URL="${INSTANCE_URL}${PACKAGES_PATH}"
 
 [ -z "${version}" ] && verspec="" || verspec="-${version}"
 
-
 URL="${CQ_PKG_URL}${GROUP_PATH}/${SNAPSHOT_NODE}/${name}${verspec}${EXTENSION}"
 
 REFERER="${CQ_PKG_URL}"
 AUTH="${username}:${password}"
 REFERER_HEADER="Referer: ${REFERER}"
 
-if [ -z "${outfile}" ]
-then
+if [ -z "${outfile}" ]; then
     outfile="${name}${verspec}-undo${EXTENSION}"
 fi
 
-if [ ${null} -eq 1 ]
-then
+if [ ${null} -eq 1 ]; then
     outfile="/dev/null"
 fi
 
 SNAPSHOT_ID="[G=${group_name}:N=${name}:V=${version}]"
 STATUS=$("${CURLBIN}" \
-        -s \
-        -I \
-        --write-out "\n%{http_code}\n" \
-        -u "${AUTH}" \
-        -H "${REFERER_HEADER}" \
-        -o /dev/null \
-        "${URL}")
+    -s \
+    -I \
+    --write-out "\n%{http_code}\n" \
+    -u "${AUTH}" \
+    -H "${REFERER_HEADER}" \
+    -o /dev/null \
+    "${URL}")
 STATUSCODE=$(echo "${STATUS}" | tail -n 1)
 "${API}" -H "${STATUSCODE}"
 EXITCODE=$?
-[ ${EXITCODE} -ne 0 ] && { \
-    echo "Cannot find snapshot for: ${SNAPSHOT_ID}" >&2; \
-    exit ${EXITCODE}; \
+[ ${EXITCODE} -ne 0 ] && {
+    echo "Cannot find snapshot for: ${SNAPSHOT_ID}" >&2
+    exit ${EXITCODE}
 }
 
-
-
 STATUS=$("${CURLBIN}" \
-        -s \
-        --write-out "%{http_code}" \
-        -u "${AUTH}" \
-        -H "${REFERER_HEADER}" \
-        -o "${outfile}" \
-        "${URL}")
+    -s \
+    --write-out "%{http_code}" \
+    -u "${AUTH}" \
+    -H "${REFERER_HEADER}" \
+    -o "${outfile}" \
+    "${URL}")
 EXITCODE=${?}
 "${API}" -C "${EXITCODE}"
 STATUSCODE=$(echo "${STATUS}" | tail -n 1)
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=$?
-if [ ${EXITCODE} -eq 0 -a ${EXITCODE2} -eq 0 ]
-then
-    if [ ! -z "${outfile}" -a "${null}" -ne 1 ]
-    then
+if [ ${EXITCODE} -eq 0 -a ${EXITCODE2} -eq 0 ]; then
+    if [ ! -z "${outfile}" -a "${null}" -ne 1 ]; then
         fullfile=$(readlink -f "${outfile}")
         echo "Uninstall snapshot saved as: ${fullfile}"
     fi
 
-    if [ ${drop} -eq 1 ]
-    then
+    if [ ${drop} -eq 1 ]; then
         STATUS=$(${CURLBIN} \
-                -s \
-                --write-out "%{http_code}" \
-                -u "${AUTH}" \
-                -H "${REFERER_HEADER}" \
-                -X DELETE \
-                -f \
-                "${URL}")
+            -s \
+            --write-out "%{http_code}" \
+            -u "${AUTH}" \
+            -H "${REFERER_HEADER}" \
+            -X DELETE \
+            -f \
+            "${URL}")
         EXITCODE=$?
         "${API}" -C ${EXITCODE}
         STATUSCODE=$(echo "$STATUS" | tail -n 1)
         "${API}" -H "${STATUSCODE}"
         EXITCODE2=$?
-        if [ ${EXITCODE} -eq 0 -a ${EXITCODE2} -eq 0 ]
-        then
+        if [ ${EXITCODE} -eq 0 -a ${EXITCODE2} -eq 0 ]; then
             echo "Snapshot dropped: ${SNAPSHOT_ID}"
         fi
     fi
 fi
 
-if [ "${STATUSCODE}" = "404" ]
-then
+if [ "${STATUSCODE}" = "404" ]; then
     echo "Getting snapshot failed: ${SNAPSHOT_ID}" >&2
-    if [ ${null} -eq 0 ]
-    then
+    if [ ${null} -eq 0 ]; then
         echo "File: ${outfile} is possibly corrupted ZIP." >&2
         echo "Verify and delete it" >&2
     fi
 fi
 
 exit $((EXITCODE + EXITCODE2))
-
diff --git a/cqtpm b/cqtpm
--- a/cqtpm
+++ b/cqtpm
@@ -13,8 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-_usage()
-{
+_usage() {
     cat <<EOT
 Usage: $(basename "${0}") [OPTION...]
 Invoke TAR PersistenceManager optimization/compaction process for specified CQ
@@ -46,25 +45,22 @@ Options:
                         compacted transaction
 
 EOT
-exit 1
+    exit 1
 }
 
 CWD=$(dirname "${0}")
 API="${CWD}/cqapi"
 "${API}" -P >/dev/null
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find or test cqapi command" >&2
     exit 1
 fi
 
 CURLBIN=$("${API}" -c)
-if [ ${?} -ne 0 ]
-then
+if [ ${?} -ne 0 ]; then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
-
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
@@ -79,33 +75,37 @@ background=true
 pooling=10
 pooling_set=0
 delayms=1
-while getopts ":fs:d:${apigetopts}" opt
-do
-  case ${opt} in
-     f)
-      background=false;;
-     s)
-      pooling=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-4); pooling_set=1;;
-     d)
-      delayms=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-3);;
+while getopts ":fs:d:${apigetopts}" opt; do
+    case ${opt} in
+    f)
+        background=false
+        ;;
+    s)
+        pooling=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-4)
+        pooling_set=1
+        ;;
+    d)
+        delayms=$(echo "${OPTARG}" | tr -cd '0-9' | cut -c1-3)
+        ;;
     \?)
-      echo "Invalid option: -${OPTARG}" >&2; _usage;;
-     :)
-      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
-  esac
+        echo "Invalid option: -${OPTARG}" >&2
+        _usage
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument." >&2
+        _usage
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [ ${pooling_set} -eq 1 -a "${background}" = "true" ]
-then
+if [ ${pooling_set} -eq 1 -a "${background}" = "true" ]; then
     _usage
 fi
 
-if [ ${#} -ge 1 -o "${passed}" -eq 0 ];
-then
+if [ ${#} -ge 1 -o "${passed}" -eq 0 ]; then
     _usage
 fi
-
 
 REFERER="${instance}/system/console/jmx/com.adobe.granite%3Atype%3DRepository"
 AUTH="${username}:${password}"
@@ -119,16 +119,14 @@ Optimization/"
 STATUS=$(${CURLBIN} \
     -s \
     -u "${AUTH}" \
-        --write-out "%{http_code}" \
+    --write-out "%{http_code}" \
     -H "${REFERERHEADER}" \
     -X POST \
     "${instance}${FILEPATH}")
 
-
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot stop TarPM optimization." >&2
     exit ${EXITCODE}
 fi
@@ -138,12 +136,10 @@ STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot stop TarPM optimization." >&2
     exit ${EXITCODE2}
 fi
-
 
 ${ECHON} "Setting TarPM compaction sleeping phase..."
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/a/TarOptimi\
@@ -151,15 +147,14 @@ zationDelay"
 STATUS=$(${CURLBIN} \
     -s \
     -u "${AUTH}" \
-     --write-out "%{http_code}" \
+    --write-out "%{http_code}" \
     -H "${REFERERHEADER}" \
     -X POST --data "value=${delayms}" \
     "${instance}${FILEPATH}")
 
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot set compaction delay to ${delay} ms." >&2
     exit ${EXITCODE}
 fi
@@ -169,15 +164,12 @@ STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot set compaction delay to ${delay} ms."
     exit ${EXITCODE2}
 fi
 
-
-if [ "${background}" = "false" ]
-then
+if [ "${background}" = "false" ]; then
     background_text="foreground"
 else
     background_text="background"
@@ -197,8 +189,7 @@ STATUS=$(${CURLBIN} \
 EXITCODE=${?}
 "${API}" -C ${EXITCODE}
 
-if [ ${EXITCODE} -ne 0 ]
-then
+if [ ${EXITCODE} -ne 0 ]; then
     echo "Cannot start TarPM compaction." >&2
     exit ${EXITCODE}
 fi
@@ -208,44 +199,35 @@ STATUS=$(echo "${STATUS}" | sed '$d;s/(null)//')
 echo "${STATUS}"
 "${API}" -H "${STATUSCODE}"
 EXITCODE2=${?}
-if [ ${EXITCODE2} -ne 0 ]
-then
+if [ ${EXITCODE2} -ne 0 ]; then
     echo "Cannot start TarPM compaction." >&2
     exit ${EXITCODE2}
 fi
 
-
 FILEPATH="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/"
-if [ "${background}" = "false" ]
-then
+if [ "${background}" = "false" ]; then
     echo "Pooling TarPM optimization status..."
     tarpm_status="1"
-    
-    while [ "${tarpm_status}" != "0" ]
-    do
+
+    while [ "${tarpm_status}" != "0" ]; do
         sleep "${pooling}s"
         STATUS=$(${CURLBIN} \
-                    -s \
-                    -u "${AUTH}" \
-                    --write-out "%{http_code}" \
-                    -H "${REFERERHEADER}" \
-                    "${instance}${FILEPATH}")
+            -s \
+            -u "${AUTH}" \
+            --write-out "%{http_code}" \
+            -H "${REFERERHEADER}" \
+            "${instance}${FILEPATH}")
         STATUSCODE=$(echo "${STATUS}" | tail -n 1)
         "${API}" -H "${STATUSCODE}"
-        if [ ${EXITCODE} -ne 0 ]
-        then
+        if [ ${EXITCODE} -ne 0 ]; then
             echo "Cannot pool properly TarPM compaction status" >&2
             exit ${EXITCODE}
         fi
 
-
-        tarpm_status=$(echo "${STATUS}" | grep TarOptimizationRunningSince\
-            | tr -cd '0-9 ' | tr -s ' ' | sed 's#^ *##' | cut -f2 -d ' ')
-        if [ -z "${tarpm_status}" ]
-        then
+        tarpm_status=$(echo "${STATUS}" | grep TarOptimizationRunningSince | tr -cd '0-9 ' | tr -s ' ' | sed 's#^ *##' | cut -f2 -d ' ')
+        if [ -z "${tarpm_status}" ]; then
             tarpm_status=0
         fi
     done
     echo "DONE"
 fi
-
