Improved detailed configuration report.
* Separated functionalities into functions
* Added new command line options
* Still modification isn't possible

diff --git a/cqcfg b/cqcfg
--- a/cqcfg
+++ b/cqcfg
@@ -49,40 +49,176 @@ EOT
 exit 1
 }
 
-
-_print_preformatted()
+_list_configurations()
 {
-    SEP='|'
+    FILEPATH="/system/console/components.json"
+    URL="${instance}${FILEPATH}"
+    REFERERHEADER="Referer: ${URL}"
+
+    STATUS=`${CURLBIN} \
+        -s \
+        --write-out "%{http_code}" \
+        -u "${AUTH}" \
+        -H "${REFERERHEADER}" \
+        "${URL}"`
+
+    EXITCODE=${?}
+    "${API}" -C ${EXITCODE}
+    if [ ${EXITCODE} -ne 0 ]
+    then
+        exit ${EXITCODE}
+    fi
+    STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
+    "${API}" -H ${STATUSCODE}
+    EXITCODE2=$?
+    if [ ${EXITCODE2} -ne 0 ]
+    then
+        exit ${EXITCODE2}
+    fi
+    CONFIG_REGEXP='"configurable":"([^"]+)"'
+    STATUS=`echo "${STATUS}"|sed -r 's#[0-9]{3}$##'`
+    CLEARED_STATUS=`echo "${STATUS}" | sed -r 's#\{#\n{#g' | \
+        grep -E -o "${CONFIG_REGEXP}" | sed -r "s#${CONFIG_REGEXP}#\1#"`
+    echo "${CLEARED_STATUS}"
+    exit 0
+}
+
+_print_general_info()
+{
+    DETAILS=`echo "${STATUS}" | sed -r "s#${PROP_REGEXP}#\1\3#"`
+    D1='"pid":"([^"]*)"'
+    D2='"title":"([^"]*)"'
+    D3='"description":"([^"]*)"'
+    D4='"bundleLocation":"([^"]*)"'
+    PID=`echo "${DETAILS}" | grep -E -o "${D1}" | sed -r "s#.*${D1}.*#\1#"`
+    TITLE=`echo "${DETAILS}" | grep -E -o "${D2}" | sed -r "s#.*${D2}.*#\1#"`
+    DESCRIPTION=`echo "${DETAILS}" | grep -E -o "${D3}" \
+        | sed -r "s#.*${D3}.*#\1#"`
+    BUNDLE=`echo "${DETAILS}" | grep -E -o "${D4}" | sed -r "s#.*${D4}.*#\1#"`
+    output="PID\t${PID}\n"
+    output="${output}TITLE\t${TITLE}\n"
+    output="${output}DESCRIPTION\t${DESCRIPTION}\n"
+    output="${output}BUNDLE\t${BUNDLE}\n"
+
+    if [ ${machine_friendly} -eq 0 -o ${info} -eq 1 ]
+    then 
+        echo "${output}" | _format_output ${machine_friendly}
+    fi
+}
+
+_print_properties()
+{
+    PROP_ENTRY_REGEXP='("[^"]+":\{"name":)'
+    PROP_ENTRIES=`echo "${PROPERTIES}" | sed -r "s#${PROP_ENTRY_REGEXP}#\n\1#g"`
+    
+    PR12='"([^"]+)":\{"name":"([^"]*)",'
+    PR3='"type":(.*),'
+    PR3S='"type":([0-9]+),'
+    PR3A='"type":(1),'
+    PR4='"value":"([^"]*)"'
+    PR4N='"value":([^,"]*)'
+    PR4A='"values":(\[[^\x5D]*\])'
+    PR5=',"description":"([^"]*)"}'
+    
+    VALUES_RG='\{"labels":\[.*\],"values":(\[.*\])\},?'
+    SWAPRG='(.*)\t(.*)\t(.*)\t(.*)\t(.*)}?'
+    TYPE_ID_RG='(.*)\t(.*)\t(.*)\t(.*)\t([0-9]+,?).*'
+    PROPS_BASIC_ROWS=`echo "${PROP_ENTRIES}" | \
+        grep -E "${PR12}" \
+        | sed -r "s#${PR12}${PR3S}${PR4}${PR5}#\1\t\4\t\2\t\5\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4N}${PR5}#\1\t\4\t\2\t\5\t\3#" \
+        | sed -r "s#${PR12}${PR3A}${PR4A}${PR5}#\1\t\4\t\2\t\5\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4A}${PR5}#\1\t\4\t\2\t\5\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4}${PR5}#\1\t\4\t\2\t\5\t\3#" \
+        | sed -r "s#${PR12}${PR3S}${PR4}#\1\t\4\t\2\t\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4N}#\1\t\4\t\2\t\t\3#" \
+        | sed -r "s#${PR12}${PR3A}${PR4A}#\1\t\4\t\2\t\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4A}#\1\t\4\t\2\t\t\3#" \
+        | sed -r "s#${PR12}${PR3}${PR4}#\1\t\4\t\2\t\t\3#" \
+        | sed -r "s#${VALUES_RG}#\1#" \
+        | sed -r "s#${TYPE_ID_RG}#\1\t\2\t\3\t\4\t#" \
+        | sed -r "s#${SWAPRG}#\1\t\2\t\3\t\5\t\4#" \
+        | sed -r 's#%22#"#g'`
+    output="ID\tVALUE\tNAME\tVALUES\tDESCRIPTION\n${PROPS_BASIC_ROWS}"
+    if [ ${long} -eq 0 ]
+    then
+        output=`${ECHO} "${output}" | cut -f1-4`
+    fi
+    if [ ${machine_friendly} -eq 0 -o ${info} -eq 0 ]
+    then 
+        echo "${output}" | _format_output ${machine_friendly}
+    fi
+}
+
+_print_configuration()
+{
+    FILEPATH="/system/console/configMgr/${config_id}"
+    URL="${instance}${FILEPATH}"
+    REFERERHEADER="Referer: ${URL}"
+
+    STATUS=`${CURLBIN} \
+        -s \
+        --write-out "%{http_code}" \
+        -u "$AUTH" \
+        -H "$REFERERHEADER" \
+        -X POST \
+        "$instance${FILEPATH}"`
+
+    EXITCODE=${?}
+    "${API}" -C $EXITCODE
+    if [ ${EXITCODE} -ne 0 ]
+    then
+        exit ${EXITCODE}
+    fi
+    STATUSCODE=`echo "${STATUS}"|grep -o -E '[0-9]{3}'|tail -n 1`
+    "${API}" -H ${STATUSCODE}
+    EXITCODE2=$?
+    if [ ${EXITCODE2} -ne 0 ]
+    then
+        exit ${EXITCODE2}
+    fi
+    
     ECHO=`which echo`
     [ $? -ne 0 -o -z "$ECHO" ] && ECHO="echo" || ECHO="$ECHO -e "
     TAB=`$ECHO "\t"`
-    STATUS=$1
-    machine_friendly=$2
-    REGEXP=".*\"id\":([0-9]+),\"name\":\"([^\"]+)\",\"fragment\":([A-Za-z]+).*,\
-\"stateRaw\":[0-9]+,\"state\":\"([A-Za-z ]+)\",\"version\":\"([^\"]+)\",\"\
-symbolicName\":\"([^\"]+)\",\"category\":\"([^\"]*)\".*"
-    filtered_items=`$ECHO -e "$STATUS" | sed 's#{#\n{#g' | grep -E "${REGEXP}"`
-    items=`$ECHO -e "$filtered_items" | sed -E "s#${REGEXP}#\1\t\6\t\4\t\5\t\2#"\
-    | sort -nk1 -t "$TAB"`
-    total=`$ECHO -e "$items" | wc -l`
-    if [ $machine_friendly -eq 0 ]
+
+    STATUS=`echo "${STATUS}" | sed -r 's#[0-9]{3}$##; s#\\\"#%22#g'`
+    PROP_REGEXP='(.*)"properties":\{(.+})}(.*)'
+    PROPERTIES=`echo "${STATUS}" | grep -E -o "${PROP_REGEXP}" | \
+        sed -r "s#${PROP_REGEXP}#\2#" `
+    
+    _print_general_info
+
+    if [ ${machine_friendly} -eq 0 ]
     then
-        $ECHO "$total bundles."
-        $ECHO ""
-        output="ID|SYMBOL|STATUS|VERSION|NAME\n"
+       ${ECHO} -e "\n\n"
     fi
-    output="${output}${items}"
-    if [ $machine_friendly -eq 1 ]
+
+    _print_properties
+}
+
+_modify_configuration()
+{
+    echo "modify"
+    # http://localhost:5410/system/console/configMgr/com.day.crx.security.token.impl.TokenCleanupTask?apply=true&action=ajaxConfigManager&scheduler.expression=23+16+*+*+*+%3F&propertylist=scheduler.expression
+}
+
+_format_output() 
+{
+    SEP='|'
+    machine_friendly=${1}
+    output=`cat -`
+    if [ ${machine_friendly} -eq 1 ]
     then
-        $ECHO -n "${output}"
+        ${ECHO} "${output}"
     else
         COLUMN=`which column`
-        if [ $? -ne 0 -o -z "$COLUMN" ]
+        if [ ${?} -ne 0 -o -z "${COLUMN}" ]
         then
             echo "Cannot find column utility"
             exit 1
         fi
-        $ECHO "${output}" | tr '\t' "$SEP" | column -xt -c 5 -s "$SEP"
+        ${ECHO} "${output}" | tr '\t' "${SEP}" | column -xt -c 5 -s "${SEP}"
     fi
 }
 
@@ -117,18 +253,35 @@ pretty=1
 machine_friendly=0
 operations=""
 long=0
-while getopts ":ljmr:s:${apigetopts}" opt; do
+original=0
+info=0
+modify=0
+propery_id=
+while getopts ":ljmns:v:${apigetopts}" opt; do
   case $opt in
      j)
-      pretty=0;;
+      original=1;;
      m)
       machine_friendly=1;;
+     n) 
+      info=1;;
      l)
       long=1;;
-     r)
-      operations="${operations} R${OPTARG}";;
+     v)
+      modify=1
+      if [ ! -z "${property_id}" ]
+      then
+          operations="${operations} ${property_id}=${OPTARG}"
+          property_id=""
+      else
+          echo "For each -v option there must be -s preceeding"\
+            "option specified " >&2
+          echo ""
+          _usage
+      fi;;
      s)
-      operations="${operations} S${OPTARG}";;
+      modify=1;
+      property_id="${OPTARG}";;
      \?)
       echo "Invalid option: -$OPTARG" >&2; _usage;;
      :)
@@ -143,230 +296,32 @@ then
 fi
 
 config_id="${1}"
-if [ ${machine_friendly} -eq 1 -a ${pretty} -eq 0 ]
+if [ ${machine_friendly} -eq 1 -a ${original} -eq 1 ]
 then
     echo "Switches: -j and -m cannot be applied together." >&2
+    echo ""
     _usage
 fi
 
 AUTH="${username}:${password}"
+config_id=`echo "${config_id}" | sed 's# #%20#g'`
 
-if [ -z "${config_id}" ]
+view_options=$((pretty+info+machine_friendly))
+if [ "${operations}" != "" -a ${view_options} -ge 1 ]
 then
-    FILEPATH="/system/console/components.json"
-    URL="${instance}${FILEPATH}"
-    REFERERHEADER="Referer: ${URL}"
-
-    STATUS=`${CURLBIN} \
-        -s \
-        --write-out "%{http_code}" \
-        -u "${AUTH}" \
-        -H "${REFERERHEADER}" \
-        "${URL}"`
-
-    EXITCODE=${?}
-    "${API}" -C ${EXITCODE}
-    if [ ${EXITCODE} -ne 0 ]
-    then
-        exit ${EXITCODE}
-    fi
-    STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-    "${API}" -H ${STATUSCODE}
-    EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
-        exit ${EXITCODE2}
-    fi
-    CONFIG_REGEXP='"configurable":"([^"]+)"'
-    STATUS=`echo "${STATUS}"|sed -r 's#[0-9]{3}$##'`
-    CLEARED_STATUS=`echo "${STATUS}" | sed -r 's#\{#\n{#g' | \
-        grep -E -o "${CONFIG_REGEXP}" | sed -r "s#${CONFIG_REGEXP}#\1#"`
-    echo "${CLEARED_STATUS}"
-    exit 0
-else 
-    config_id=`echo "${config_id}" | sed 's# #%20#g'`
-    FILEPATH="/system/console/configMgr/${config_id}"
-    URL="${instance}${FILEPATH}"
-    REFERERHEADER="Referer: ${URL}"
-
-    STATUS=`${CURLBIN} \
-        -s \
-        --write-out "%{http_code}" \
-        -u "$AUTH" \
-        -H "$REFERERHEADER" \
-        -X POST \
-        "$instance${FILEPATH}"`
-
-    EXITCODE=${?}
-    "${API}" -C $EXITCODE
-    if [ ${EXITCODE} -ne 0 ]
-    then
-        exit ${EXITCODE}
-    fi
-    STATUSCODE=`echo "${STATUS}"|grep -o -E '[0-9]{3}'|tail -n 1`
-    "${API}" -H ${STATUSCODE}
-    EXITCODE2=$?
-    if [ ${EXITCODE2} -ne 0 ]
-    then
-        exit ${EXITCODE2}
-    fi
-    
-    SEP='|'
-    ECHO=`which echo`
-    [ $? -ne 0 -o -z "$ECHO" ] && ECHO="echo" || ECHO="$ECHO -e "
-    TAB=`$ECHO "\t"`
-
-    STATUS=`echo "${STATUS}" | sed -r 's#[0-9]{3}$##'`
-    PROP_REGEXP='(.*)"properties":\{(.+})}(.*)'
-    PROPERTIES=`echo "${STATUS}" | sed -r "s#${PROP_REGEXP}#\2#"`
-    DETAILS=`echo "${STATUS}" | sed -r "s#${PROP_REGEXP}#\1\3#"`
-    D1='"pid":"([^"]*)"'
-    D2='"title":"([^"]*)"'
-    D3='"description":"([^"]*)"'
-    D4='"bundleLocation":"([^"]*)"'
-    PID=`echo "${DETAILS}" | grep -E -o "${D1}" | sed -r "s#.*${D1}.*#\1#"`
-    TITLE=`echo "${DETAILS}" | grep -E -o "${D2}" | sed -r "s#.*${D2}.*#\1#"`
-    DESCRIPTION=`echo "${DETAILS}" | grep -E -o "${D3}" \
-        | sed -r "s#.*${D3}.*#\1#"`
-    BUNDLE=`echo "${DETAILS}" | grep -E -o "${D4}" | sed -r "s#.*${D4}.*#\1#"`
-    output="PID\t${PID}\n"
-    output="${output}TITLE\t${TITLE}\n"
-    output="${output}DESCRIPTION\t${DESCRIPTION}\n"
-    output="${output}BUNDLE\t${BUNDLE}\n"
-    if [ ${machine_friendly} -eq 1 ]
-    then
-        ${ECHO} "${output}"
-    else
-        COLUMN=`which column`
-        if [ ${?} -ne 0 -o -z "${COLUMN}" ]
-        then
-            echo "Cannot find column utility"
-            exit 1
-        fi
-        ${ECHO} "${output}" | tr '\t' "${SEP}" | column -xt -c 5 -s "${SEP}"
-    fi
-
-    
-    echo ""
-    echo ""
-    PROP_ENTRY_REGEXP='("[^"]+":\{"name":)'
-    PROP_ENTRIES=`echo "${PROPERTIES}" | sed -r "s#${PROP_ENTRY_REGEXP}#\n\1#g"`
-    
-    PR1='"([^"]+)":\{"name":"([^"]*)",'
-    PR2='"type":(.*),'
-    PR2S='"type":([0-9]+),'
-    PR2A='"type":(1),'
-    PR3='"value":"([^"]*)",'
-    PR3N='"value":([^,"]*),'
-    PR3A='"values":(\[[^\x5D]*\]),'
-    PR4='"description":"(.*)"}'
-    
-    VALUES_RG='\{"labels":\[.*\],"values":(\[.*\])\},'
-    SWAPRG='(.*)\t(.*)\t(.*)\t(.*)\t(.*)}?'
-    TYPE_ID_RG='(.*)\t(.*)\t(.*)\t(.*)\t([0-9]+,?).*'
-    PROPS_BASIC_ROWS=`echo "${PROP_ENTRIES}" | \
-        sed -r "s#${PR1}${PR2S}${PR3}${PR4}#\1\t\4\t\2\t\5\t\3#" \
-        | sed -r "s#${PR1}${PR2}${PR3N}${PR4}#\1\t\4\t\2\t\5\t\3#" \
-        | sed -r "s#${PR1}${PR2A}${PR3A}${PR4}#\1\t\4\t\2\t\5\t\3#" \
-        | sed -r "s#${PR1}${PR2}${PR3}${PR4}#\1\t\4\t\2\t\5\t\3#" \
-        | sed -r "s#${VALUES_RG}#\1#" \
-        | sed -r "s#${TYPE_ID_RG}#\1\t\2\t\3\t\4\t#" \
-        | sed -r "s#${SWAPRG}#\1\t\2\t\3\t\5\t\4#"`
-    output="ID\tVALUE\tNAME\tVALUES\tDESCRIPTION\n${PROPS_BASIC_ROWS}"
-    if [ ${long} -eq 0 ]
-    then
-        output=`${ECHO} "${output}" | cut -f1-4`
-    fi
-    
-    if [ ${machine_friendly} -eq 1 ]
-    then
-        ${ECHO} "${output}"
-    else
-        COLUMN=`which column`
-        if [ ${?} -ne 0 -o -z "${COLUMN}" ]
-        then
-            echo "Cannot find column utility"
-            exit 1
-        fi
-        ${ECHO} "${output}" | tr '\t' "${SEP}" | column -xt -c 5 -s "${SEP}"
-    fi
-
-fi
-
-#"format":{"name":"Format","type":1,"value":"Basic","description":"Indication of the format in which the user ID is provided. Use \"Basic\" if the user ID is encoded in the HTTP Basic Authentication format, \"AsIs\" if the user ID is provided in plain text or any regular expression applied value should be used as is or any regular expression. (format)"},
-
-# http://localhost:5410/system/console/configMgr/com.day.crx.security.token.impl.TokenCleanupTask?apply=true&action=ajaxConfigManager&scheduler.expression=23+16+*+*+*+%3F&propertylist=scheduler.expression
-
-if [ "$operations" != "" -a \( $pretty -eq 0 -o $machine_friendly -eq 1 \) ]
-then
-    echo "View options -m or -j cannot be applied together with operations: -r/-s" >&2
+    echo "View options -m, -j or -n cannot be applied together " \
+        "with modify operations: -s/-v" >&2
     exit 2
 fi
 
-if [ "$operations" != "" ]
+if [ -z "${config_id}" ]
 then
-    bundle_map=`_print_preformatted "$STATUS" 1 | cut -f 1,2`
-    operations_by_id=""
-    for operation in $operations
-    do
-        action=`echo "$operation" | cut -c1`
-        bundle=`echo "$operation" | cut -c2-`
-        if [ "$action" != "R" -a "$action" != "S" ]
-        then
-            echo "Only run/stop operations are permitted for bundles" >&2
-            exit 2
-        fi
-        bundle_escaped=`echo "${bundle}" | sed -r 's#\.#\\.#g' `
-        id=`echo "$bundle_map" | grep -E "[[:space:]]+${bundle_escaped}$" | cut -f1`
-        if [ "$id" = "" ]
-        then
-            echo "Cannot find specified bundle: ${bundle}" >&2
-            exit 3
-        else
-            operations_by_id="${operations_by_id} ${action}${id}${bundle}"
-        fi
-    done
-    for op in $operations_by_id
-    do
-        action=` echo "$op" | cut -c1 `
-        bundle_spec=` echo "$op" | cut -c2- `
-        bundle_id=` echo "$bundle_spec" | sed -r 's/^([0-9]+).+$/\1/' `
-        bundle=` echo "$bundle_spec" | sed -r 's/^[0-9]+(.+)$/\1/' `
-
-        [ "$action" = "R" ] && activity="Running bundle: " || activity="Stopping bunle: "
-        [ "$action" = "R" ] && optype="start" || optype="stop"
-        post_param="action=${optype}"
-
-        echo "${activity}${bundle} (#${bundle_id})"
-        STATUS=`$CURLBIN \
-                -s \
-                --write-out "%{http_code}" \
-                -u "$AUTH" \
-                -H "$REFERERHEADER" \
-                -d "$post_param" \
-                "$instance${FILEPATH}/${bundle_id}"`
-
-        EXITCODE=$?
-        $API -C $EXITCODE
-        if [ $EXITCODE -ne 0 ]
-        then
-            exit $EXITCODE
-        fi
-        STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-        $API -H ${STATUSCODE}
-        EXITCODE2=$?
-        if [ $EXITCODE2 -ne 0 ]
-        then
-            exit $EXITCODE2
-        fi
-    done
-    exit 0
+    _list_configurations
+elif [ ${modify} -eq 0 ]
+then
+    _print_configuration
+else
+    _modify_configuration
 fi
 
-#if [ $pretty -eq 1 ]
-#then
-#    _print_preformatted "$STATUS" $machine_friendly
-#else
-#    echo "$STATUS"
-#fi
 
