Shellcheck fixes. Compatibility fixes for cqcfgls * Replaced sed -r with ${SEDX}. * Replaced ${ECHO} with printf

diff --git a/cqcfgls b/cqcfgls
--- a/cqcfgls
+++ b/cqcfgls
@@ -16,7 +16,7 @@
 _usage()
 {
     cat << EOT
-Usage: `basename "${0}"` [OPTION...]
+Usage: $(basename "${0}") [OPTION...]
 Return CQ instance list of OSGI configurations using instance URL.
 
 Examples:
@@ -41,42 +41,42 @@ _list_configurations()
     URL="${instance}${FILEPATH}"
     REFERERHEADER="Referer: ${URL}"
 
-    STATUS=`${CURLBIN} \
+    STATUS=$(${CURLBIN} \
         -s \
         --write-out "%{http_code}" \
         -u "${AUTH}" \
         -H "${REFERERHEADER}" \
-        "${URL}"`
+        "${URL}")
 
     EXITCODE=${?}
-    "${API}" -C ${EXITCODE}
+    "${API}" -C "${EXITCODE}"
     if [ ${EXITCODE} -ne 0 ]
     then
         exit ${EXITCODE}
     fi
-    STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-    "${API}" -H ${STATUSCODE}
+    STATUSCODE=$(echo "$STATUS" | grep -o -E '[0-9]{3}' | tail -n 1)
+    "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
     if [ ${EXITCODE2} -ne 0 ]
     then
         exit ${EXITCODE2}
     fi
     CONFIG_REGEXP='"configurable":"([^"]+)"'
-    STATUS=`echo "${STATUS}"|sed -r 's#[0-9]{3}$##'`
+    STATUS=$(echo "${STATUS}" | ${SEDX} 's#[0-9]{3}$##')
 
-    CLEARED_STATUS=`echo "${STATUS}" | sed -r 's#\{#\n{#g' | \
-        grep -E -o "${CONFIG_REGEXP}" | sed -r "s#${CONFIG_REGEXP}#\1#"`
+    CLEARED_STATUS=$(echo "${STATUS}" | ${SEDX} 's#\{#\n{#g' | \
+        grep -E -o "${CONFIG_REGEXP}" | ${SEDX} "s#${CONFIG_REGEXP}#\1#")
 
     FILEPATH="/system/console/config/Configurations.nfo"
     URL="${instance}${FILEPATH}"
     REFERERHEADER="Referer: ${URL}"
 
-    STATUS=`${CURLBIN} \
+    STATUS=$(${CURLBIN} \
         -s \
         --write-out "%{http_code}" \
         -u "${AUTH}" \
         -H "${REFERERHEADER}" \
-        "${URL}"`
+        "${URL}")
 
     EXITCODE=${?}
     "${API}" -C ${EXITCODE}
@@ -84,26 +84,27 @@ _list_configurations()
     then
         exit ${EXITCODE}
     fi
-    STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
-    "${API}" -H ${STATUSCODE}
+    STATUSCODE=$(echo "${STATUS}" | grep -o -E '[0-9]{3}' | tail -n 1)
+    "${API}" -H "${STATUSCODE}"
     EXITCODE2=$?
     if [ ${EXITCODE2} -ne 0 ]
     then
         exit ${EXITCODE2}
     fi
 
-    STATUS=`echo "${STATUS}"|sed -r 's#[0-9]{3}$##'`
-    CLEARED_STATUS2=`echo "${STATUS}" | grep '^PID' | sed -r 's#&nbsp;# #g' | \
-        sed -r 's#<br/>##g' | cut -f2- -d '=' | sed -r 's#^[ ]+##; s#[ ]+$##'`
+    STATUS=$(echo "${STATUS}" | sed -r 's#[0-9]{3}$##')
+    CLEARED_STATUS2=$(echo "${STATUS}" | grep '^PID' | ${SEDX} 's#&nbsp;# #g' \
+        | ${SEX} 's#<br/>##g' | cut -f2- -d '=' \
+        | ${SEDX} 's#^[ ]+##; s#[ ]+$##')
 
-    ${ECHO} "${CLEARED_STATUS}\n${CLEARED_STATUS2}" | sort | uniq
+    printf "%s\n%s" "${CLEARED_STATUS}" "${CLEARED_STATUS2}" | sort | uniq
     exit 0
 }
 
 
-CWD=`dirname "${0}"`
+CWD=$(dirname "${0}")
 API="$CWD/cqapi"
-APITEST=`"${API}" -P`
+"${API}" -P >/dev/null 2>/dev/null
 
 if [ ${?} -ne 0 ]
 then
@@ -111,40 +112,39 @@ then
     exit 1
 fi
 
-CURLBIN=`"${API}" -c`
+CURLBIN=$("${API}" -c)
 if [ ${?} -ne 0 ]
 then
     echo "Fatal: cannot find curl" >&2
     exit 1
 fi
 
+SEDX=$("${API}" -s)
 
 # API common options
-cmdapi=`    "${API}" -P ${@}`
-username=`  echo "${cmdapi}" | cut -f1`
-password=`  echo "${cmdapi}" | cut -f2`
-instance=`  echo "${cmdapi}" | cut -f3`
-passed=`    echo "${cmdapi}" | cut -f4`
-apigetopts=`echo "${cmdapi}" | cut -f5`
+cmdapi=$("${API}" -P "${@}")
+username=$(echo "${cmdapi}" | cut -f1)
+password=$(echo "${cmdapi}" | cut -f2)
+instance=$(echo "${cmdapi}" | cut -f3)
+passed=$(echo "${cmdapi}" | cut -f4)
+apigetopts=$(echo "${cmdapi}" | cut -f5)
 
 while getopts ":${apigetopts}" opt; do
-  case $opt in
+  case "${opt}" in
      \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
+      echo "Invalid option: -${OPTARG}" >&2; _usage;;
      :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
+      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
   esac
 done
 shift $((OPTIND-1))
 
-if [ ${#} -gt 0 -o ${passed} -eq 0 ]
+if [ ${#} -gt 0 -o "${passed}" -eq 0 ]
 then
     _usage
 fi
 
 AUTH="${username}:${password}"
 
-ECHO=`which echo`
-[ $? -ne 0 -o -z "$ECHO" ] && ECHO="echo" || ECHO="$ECHO -e "
 _list_configurations
 
