CQM-109 Problem with accessing tools with whitespace characters included in path
* Secured: cqclr command

diff --git a/cqclr b/cqclr
--- a/cqclr
+++ b/cqclr
@@ -16,7 +16,7 @@
 _usage()
 {
 	cat << EOT
-Usage: `basename $0` [OPTION...]
+Usage: `basename "${0}"` [OPTION...]
 Clear cache for specified dispatcher (-i option). By default clear the whole
 cache / node or specified node provided by -r option. To match specific
 dispatcher flush cache server configuration use -v domain option to request
@@ -46,16 +46,16 @@ EOT
 exit 1
 }
 
-CWD=`dirname $0`
+CWD=`dirname "${0}"`
 API="$CWD/cqapi"
-APITEST=`$API -P`
-if [ $? -ne 0 ]
+APITEST=`"${API}" -P`
+if [ ${?} -ne 0 ]
 then
 	echo "Fatal: cannot find or test cqapi command" >&2
 	exit 1
 fi
 
-CURLBIN=`$API -c`
+CURLBIN=`"${API}" -c`
 if [ $? -ne 0 ]
 then
 	echo "Fatal: cannot find curl" >&2
@@ -64,7 +64,7 @@ fi
 
 
 # API common options
-cmdapi=`    $API -P $@`
+cmdapi=`    "${API}" -P $@`
 username=`  echo "${cmdapi}" | cut -f1`
 password=`  echo "${cmdapi}" | cut -f2`
 instance=`  echo "${cmdapi}" | cut -f3`
@@ -74,29 +74,29 @@ apigetopts=`echo "${cmdapi}" | cut -f5`
 path="/"
 vhost=""
 while getopts ":r:v:${apigetopts}" opt; do
-  case $opt in
+  case ${opt} in
      r)
-      path="$OPTARG";;
+      path="${OPTARG}";;
      v)
-      vhost="$OPTARG";;
+      vhost="${OPTARG}";;
     \?)
-      echo "Invalid option: -$OPTARG" >&2; _usage;;
+      echo "Invalid option: -${OPTARG}" >&2; _usage;;
      :)
-      echo "Option -$OPTARG requires an argument." >&2; _usage;;
+      echo "Option -${OPTARG} requires an argument." >&2; _usage;;
   esac
 done
 shift $((OPTIND-1))
 
-if [ $# -ge 1 -o $passed -eq 0 ]
+if [ ${#} -ge 1 -o ${passed} -eq 0 ]
 then
 	_usage
 fi
 
 
 URL="${instance}/dispatcher/invalidate.cache"
-REFERER=$URL
-AUTH="$username:$password"
-REFERERHEADER="Referer: $REFERER"
+REFERER=${URL}
+AUTH="${username}:${password}"
+REFERERHEADER="Referer: ${REFERER}"
 VHOSTHEADER=""
 VHOSTOPTION=""
 echo "Clearing dispatcher cache:"
@@ -104,7 +104,7 @@ echo "                     path: ${path}"
 
 if [ "$vhost" != "" ]
 then
-    VHOSTHEADER="Host: $vhost"
+    VHOSTHEADER="Host: ${vhost}"
     echo "           requested host: ${vhost}"
 fi
 
@@ -115,23 +115,23 @@ echo ""
 STATUS=`$CURLBIN -s -X POST \
         --output /dev/null \
         --write-out %{http_code} \
-        -u "$AUTH" \
+        -u "${AUTH}" \
         -H "CQ-Action: Delete" \
-        -H "CQ-Handle: $path" \
+        -H "CQ-Handle: ${path}" \
         -H "Content-Length: 0" \
-        -H "$VHOSTHEADER" \
+        -H "${VHOSTHEADER}" \
         "${URL}"`
-EXITCODE=$?
-$API -C $EXITCODE
-if [ $EXITCODE -ne 0 ]
+EXITCODE=${?}
+"${API}" -C ${EXITCODE}
+if [ ${EXITCODE} -ne 0 ]
 then
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
-$API -H $STATUS
-EXITCODE=$?
-if [ $EXITCODE -ne 0 ]
+"${API}" -H ${STATUS}
+EXITCODE=${?}
+if [ ${EXITCODE} -ne 0 ]
 then
-    exit $EXITCODE
+    exit ${EXITCODE}
 fi
 
 echo "Clearing cache successful."
