CQM-57 Handling GC exceptions carefully
Cqgc exception when already running.
Added -f switch to stop current GC session prior starting new one.

diff --git a/cqgc b/cqgc
--- a/cqgc
+++ b/cqgc
@@ -27,8 +27,9 @@ Examples:
                                 # process 
   cqgc -i http://localhost:5510 # Invokes garbace collection for localhost
                                 # instance on tcp port 5510
-  cqgc -p secret                # Invokes garbage collection using provided 
-                                # login password: secret
+  cqgc -f -p secret             # Invokes garbage collection using provided
+                                # login password: secret. Stops current GC
+                                # session if running
 
 Options:
 
@@ -36,6 +37,7 @@ Options:
   -p                    use provided password for authentication
   -i                    use specified instance URL to connect
   -d                    changes sleeping phase for each node  
+  -f                    stops current GC session
 
 EOT
 exit 1
@@ -68,10 +70,13 @@ apigetopts=`echo "${cmdapi}" | cut -f5`
 
 # Custom arguments
 delay_ms=15
-while getopts ":d:${apigetopts}" opt; do
+force_stop=0
+while getopts ":d:f${apigetopts}" opt; do
   case $opt in
      d)  
       delay_ms=`echo $OPTARG|tr -cd '[:digit:]'`;;
+     f)
+      force_stop=1;;
     \?)
       echo "Invalid option: -$OPTARG" >&2; _usage;;
      :)
@@ -92,7 +97,44 @@ FILEPATH1="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/a/DataStor\
 eGarbageCollectionDelay"
 FILEPATH2="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/runData\
 StoreGarbageCollection/java.lang.Boolean"
+FILEPATH3="/system/console/jmx/com.adobe.granite%3Atype%3DRepository/op/stopDat\
+aStoreGarbageCollection"
 REFERERHEADER="Referer: $REFERER"
+
+# Stopping GC sleeping phase delay
+if [ $force_stop -eq 1 ]
+then
+    echo -n "Stopping DataStore garbage collection (if working)..."
+    STATUS=`$CURLBIN \
+           -s \
+           --write-out "%{http_code}" \
+           -u "$AUTH" \
+           -H "$REFERERHEADER" \
+           -X POST \
+           "$instance${FILEPATH3}"`
+
+    EXITCODE=$?
+    $API -C $EXITCODE
+
+    if [ $EXITCODE -ne 0 ]
+    then
+        echo "Cannot stop current garbage collection." >&2
+        exit $EXITCODE
+    fi
+
+    STATUSCODE=`echo "$STATUS"|tail -n 1`
+    STATUS=`echo "$STATUS"|sed '$d;s/(null)//;s/^$/DONE/;'`
+    echo "${STATUS}"
+    $API -H $STATUSCODE
+    EXITCODE2=$?
+    if [ $EXITCODE2 -ne 0 ]
+    then
+        echo "Cannot stop current garbage collection." >&2
+        exit $EXITCODE2
+    fi
+    sleep 5s
+fi
+
 
 # Setting GC sleeping phase delay
 echo -n "Setting DataStore garbage collection sleeping phase..."
@@ -114,7 +156,7 @@ then
 fi
 
 STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;s/(null)//'`
+STATUS=`echo "$STATUS"|sed '$d;s/(null)//;s/^$/DONE/;'`
 echo "${STATUS}"
 $API -H $STATUSCODE
 EXITCODE2=$?
@@ -127,11 +169,11 @@ fi
 # Invoke GC process in the foreground
 echo -n "Running DataStore garbage collection..."
 STATUS=`$CURLBIN \
-	-s \
-        --write-out "%{http_code}" \
-	-u "$AUTH" \
-	-H "$REFERERHEADER" \
-	-X POST --data delete=true \
+    -s \
+    --write-out "%{http_code}" \
+    -u "$AUTH" \
+    -H "$REFERERHEADER" \
+    -X POST --data delete=true \
 	"$instance${FILEPATH2}"`
 
 EXITCODE=$?
@@ -144,7 +186,12 @@ then
 fi
 
 STATUSCODE=`echo "$STATUS"|tail -n 1`
-STATUS=`echo "$STATUS"|sed '$d;s/(null)//'`
+STATUS=`echo "$STATUS"|sed '$d;s/(null)//;s/^$/DONE/'`
+is_exception=`echo "$STATUS"|$API -e`
+if [ $is_exception -ge 0 ]
+then
+    STATUS=`echo "$STATUS"|$API -E`
+fi
 echo "${STATUS}"
 $API -H $STATUSCODE
 EXITCODE2=$?
