CQM-149 echo -e doesn't work on Mac OS X
* Added cqapi -w flag to return correct extended echo command with escape
  sequences interpretation turned on
* Added redirection to stderr on some command location error messages instead
  of stdout
* Switched tools that outputs structured data heavily to use cqapi -w option to
  gather ECHOX extended echo behavior

diff --git a/cqosgi b/cqosgi
--- a/cqosgi
+++ b/cqosgi
@@ -54,38 +54,36 @@ exit 1
 _print_preformatted()
 {
     SEP='|'
-    ECHO=$(which echo)
-    [ ${?} -ne 0 -o -z "${ECHO}" ] && ECHO="echo" || ECHO="${ECHO} -e "
-    TAB=$(${ECHO} "\t")
+    TAB=$(${ECHOX} "\t")
     STATUS=${1}
     machine_friendly=${2}
     REGEXP=".*\"id\":([0-9]+),\"name\":\"([^\"]+)\",\"fragment\":([A-Za-z]+).*,\
 \"stateRaw\":[0-9]+,\"state\":\"([A-Za-z ]+)\",\"version\":\"([^\"]+)\",\"\
 symbolicName\":\"([^\"]+)\",\"category\":\"([^\"]*)\".*"
-    filtered_items=$(${ECHO} -e "${STATUS}" | sed 's#{#\n{#g' \
+    filtered_items=$(${ECHOX} "${STATUS}" | sed 's#{#\n{#g' \
         | grep -E "${REGEXP}")
-    items=$(${ECHO} -e "${filtered_items}" \
+    items=$(${ECHOX} "${filtered_items}" \
         | ${SEDX} "s#${REGEXP}#\1\t\6\t\4\t\5\t\2#"\
         | sort -nk1 -t "${TAB}")
-    total=$(${ECHO} -e "${items}" | wc -l)
+    total=$(${ECHOX} "${items}" | wc -l)
     if [ "${machine_friendly}" -eq 0 ]
     then
-        ${ECHO} "${total} bundles."
-        ${ECHO} ""
+        ${ECHOX} "${total} bundles."
+        ${ECHOX} ""
         output="ID|SYMBOL|STATUS|VERSION|NAME\n"
     fi
     output="${output}${items}"
     if [ "${machine_friendly}" -eq 1 ]
     then
-        ${ECHO} "${output}"
+        ${ECHOX} "${output}"
     else
         COLUMN=$(which column)
         if [ ${?} -ne 0 -o -z "${COLUMN}" ]
         then
-            echo "Cannot find column utility"
+            echo "Cannot find column utility" >&2
             exit 1
         fi
-        ${ECHO} "${output}" | tr '\t' "${SEP}" | column -xt -c 5 -s "${SEP}"
+        ${ECHOX} "${output}" | tr '\t' "${SEP}" | column -xt -c 5 -s "${SEP}"
     fi
 }
 
@@ -106,6 +104,7 @@ then
     exit 1
 fi
 SEDX=$("${API}" -s)
+ECHOX=$("${API}" -w)
 
 # API common options
 cmdapi=$("${API}" -P "${@}")
