CQM-41 cqwfl output format improvement
By default human-readable format is returned by cqwfl tool.
To see original JSON response -j option should be passed.
To parse response (tab-delimited fields) -m option should be passed.

-m and default behavior use seq tool which is not portable to i.e.
BSD systems.

diff --git a/cqwfl b/cqwfl
--- a/cqwfl
+++ b/cqwfl
@@ -17,8 +17,8 @@ _usage()
 {
 	cat << EOT
 Usage: `basename $0` [OPTION...] 
-Returns CQ instance active workflows status in form of JSON data using instance
-URL.
+Returns CQ instance active workflows status in pretty-printed form using
+instance URL. Use -j to return original JSON form. Use -m for machine
  
 Examples:
   cqwfl -u admin                 # Returns JSON data with active workflows from
@@ -32,15 +32,76 @@ Options:
   -u                    use specified usernamed for connection
   -p                    use provided password for authentication
   -i                    use specified instance URL to connect
-
-
+  -j                    returns workflow report in original JSON form
+  -m                    returns workflow report in machine-friendly form
+                        (fields separated by tabs) without header
 EOT
 exit 1
+}
+
+_extract_json()
+{
+    echo "$1"|grep -oE '"'$2'"[ ]*:[ ]*"[^"]+"'|cut -f2- -d ":"|
+        sed 's#"##g'
+}
+
+_extract_json_number()
+{
+    echo "$1"|grep -oE '"'$2'"[ ]*:[ ]*[0-9]+'|cut -f2- -d ":"|
+        sed 's#"##g'|grep -Eo '[0-9]+'
+}
+
+_print_preformatted()
+{
+    STATUS=$1
+    machine_friendly=$2
+    total=`echo "$STATUS"|sed 's#{#\n{#g; s#\[#\n\[#g'|grep -Eo \
+        '\"results\":"?[0-9]+"?'|cut -f2 -d ':'`
+    items=`echo "$STATUS"|sed 's#{#\n{#g;'|grep -E \
+        '"item".+"state".+"initiator".+"startTime".+"model".+"payload".+'`
+    items_count=`echo "$items"|wc -l`
+    if [ $machine_friendly -eq 0 ]
+    then
+        echo "$total active workflows."
+        echo ""
+        output="STARTTIME|STATE|INITIATOR|MODEL|ITEM|PAYLOAD\n"
+    fi
+    for idx in `seq 1 $items_count`
+    do
+        line=`echo "${items}"|head -n $idx|tail -n 1`
+        item=`_extract_json "$line" item`
+        state=`_extract_json "$line" state`
+        initiator=`_extract_json "$line" initiator`
+        startTime=`_extract_json_number "$line" startTime`
+        model=`_extract_json "$line" model`
+        payload=`_extract_json "$line" payload`
+        if [ $machine_friendly -eq 1 ]
+        then
+            oneline="$startTime\t$state\t$initiator\t$model\t$item\t$payload\n"
+            output="${output}${oneline}"
+        else
+            oneline="$startTime|$state|$initiator|$model|$item|$payload\n"
+            output="${output}${oneline}"
+        fi
+    done
+    if [ $machine_friendly -eq 1 ]
+    then
+        ECHO=`which echo`
+        if [ $? -ne 0 ]
+        then
+            echo "${output}"
+        else
+            $ECHO -en "${output}"
+        fi
+    else
+        echo "${output}"|column -xt -c 5 -s "|"
+    fi
 }
 
 CWD=`dirname $0`
 API="$CWD/cqapi"
 APITEST=`$API -P`
+
 if [ $? -ne 0 ]
 then
 	echo "Fatal: cannot find or test cqapi command" >&2
@@ -64,9 +125,15 @@ passed=`    echo "${cmdapi}" | cut -f4`
 apigetopts=`echo "${cmdapi}" | cut -f5`
 
 # Custom arguments
-while getopts ":${apigetopts}" opt; do
+pretty=1
+machine_friendly=0
+while getopts ":jm${apigetopts}" opt; do
   case $opt in
-    \?)
+     j)
+      pretty=0;;
+     m)
+      machine_friendly=1;;
+     \?)
       echo "Invalid option: -$OPTARG" >&2; _usage;;
      :)
       echo "Option -$OPTARG requires an argument." >&2; _usage;;
@@ -74,9 +141,15 @@ while getopts ":${apigetopts}" opt; do
 done
 shift $((OPTIND-1))
 
-if [ $# -gt 0 -o $passed -eq 0 ];
+if [ $# -gt 0 -o $passed -eq 0 ]
 then
 	_usage
+fi
+
+if [ $machine_friendly -eq 1 -a $pretty -eq 0 ]
+then
+    echo "Switches: -j and -m cannot be applied together."
+    _usage
 fi
 
 REFERER="$instance/libs/cq/workflow/content/console/instances.html"
@@ -93,10 +166,23 @@ STATUS=`$CURLBIN \
 
 EXITCODE=$?
 $API -C $EXITCODE
+if [ $EXITCODE -ne 0 ]
+then
+    exit $EXITCODE
+fi
 STATUSCODE=`echo "$STATUS"|grep -o -E '[0-9]{3}'|tail -n 1`
 $API -H ${STATUSCODE}
 EXITCODE2=$?
+if [ $EXITCODE2 -ne 0 ]
+then
+    exit $EXITCODE2
+fi
 STATUS=`echo "$STATUS"|sed -r 's#[0-9]{3}$##'`
-echo "${STATUS}"
-exit $((EXITCODE + EXITCODE2))
+
+if [ $pretty -eq 1 ]
+then
+    _print_preformatted "$STATUS" $machine_friendly
+else
+    echo "$STATUS"
+fi
 
